### ISSUE TITLE
Feature request: on game exit return to the last menu position

### ISSUE THREAD

**Issue by vvranjek** [libretro/RetroArch#12191]
When exiting a game/rom I would prefer to continue browsing at the last game I was playing. Instead I have to navigate from beginning every time as if I iust launched retroarch. I believe this to be counterintuitive and for me very annoying.

Currnet flow: playing game -> exit -> land on quick menu -> back -> land in the beginning -> navigate to playlist -> navigate to game (could be 100s of games away) -> play game

Preferred flow: playing game -> exit -> land on quick menu -> back -> land in last open game  -> navigate to next game (very likely to be "1 click" away) -> play game

As you see every time I switch a game I could save much time and button presses whenever I want to switch to another game. I would prefer this user experience very much!

I am a developer myself and don't mind contributing if someone would point me to the right place in the code. I don't have time to learn the whole project for this (i believe to be) relatively easy fix.

Nonetheless, great software, thanks to all the people who helped make this legendary piece of software!

**Comment by sonninnos** [comment]
This has been done for ages. How old version are you running?

**Comment by keithbowes** [comment]
I'm running 1.9.0 and it doesn't do this.  If you enter the menu and then exit the menu but keep the game running and then reenter the menu, it remembers your position.  But if you exit the emulator and start back up, it doesn't remember your position.

**Comment by vvranjek** [comment]
@sonninnos It's version 1.9.0. Maybe you dont understand what I mean, here is a video: https://m.youtube.com/watch?v=DgitN-t_bCk&feature=youtu.be

**Comment by sonninnos** [comment]
Yep, the current mechanism requires the user to do "Close Content" to go back to the previous point in the playlist. Not sure if there is way around that..

**Comment by vvranjek** [comment]
@sonninnos I tried, it does not, have look at the video: https://m.youtube.com/watch?v=lQ3TzDSxmwk&feature=youtu.be

**Comment by sonninnos** [comment]
Huh, here it does work..

**Comment by vvranjek** [comment]
It would be great if someone can confirm this behavior on Nintendo Switch?

**Comment by sonninnos** [comment]
Is that 1.9.0 the ancient stable? I think it was fixed later than that. Try updating first to 1.9.1.

**Comment by illando** [comment]
This is solved but not in iOS. Unfortunately, when you select "close content" RA goest to the 1st game of the playlist of the game you were playing instead of landing on quick menu.
@yoshisuga

**Comment by vidvranjek** [comment]
@illando In which commit/version was it solved?

**Comment by sonninnos** [comment]
This is a "static" build thing only.

**Comment by vvranjek** [comment]
What  static build thing only? This means nothing. If there is no
commit/fix, then it is not solved, the issue is still there.

**Comment by sonninnos** [comment]
As in platforms that can't load dynamic libraries. Just try with a desktop version to see the difference.

**Comment by vidvranjek** [comment]
I understand that it works correctly on some platforms, but not others. I also understand that it is not easy to make it work perfectly on all platforms. But the issue is still not 'solved' until it works correctly on all supported platforms. This is like cleaning the room by stuffing everything under the bed. It should be at least logged somewhere as 'known issues', marked as 'not fixed' and put aside to be potentially fixed in the future.
