### ISSUE TITLE
Fix Xbox one and Xbox series x and s threaded video crashes

### ISSUE THREAD

**Issue by Jackmath5** [libretro/RetroArch#13341]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Fix up Audio latency glitches and Threaded video crashes on Xbox one and Xbox series x/s

### Expected behavior

Can you fix up threaded video and audio latency for Xbox one and Xbox series x?

### Actual behavior

When Threaded video is turn on the Retroarch crashed on Xbox one and Xbox series x/s, while audio latency is on from 0 to 11 it sounds glitchy.

### Steps to reproduce the bug

1. Fix up threaded video crashes
2. Fix up audio latency
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: any version

### Environment information

- OS: Xbox one and Xbox series x
- Compiler: [In case you are running local builds]

**Comment by LibretroAdmin** [comment]
Audio latency 0-11 is unrealistic, won't fix.

**Comment by LibretroAdmin** [comment]
@TheRhysWyrill do you know what he is referring to with regards to these threaded video crashes? Have they been resolved by now?

**Comment by TheRhysWyrill** [comment]
@LibretroAdmin I believe he's referring to the fact that trying to enable the Threaded Video option results in a black screen hard crash, just tested it with the latest master and can confirm it still happens.

**Comment by basharast** [comment]
There are many issues related to this:
## First
Those lines [here 781](https://github.com/libretro/RetroArch/blob/8a6f7e6fffce7e9ea5bffcb24a4a797fc9635781/uwp/uwp_main.cpp#L781) and [here 821](https://github.com/libretro/RetroArch/blob/8a6f7e6fffce7e9ea5bffcb24a4a797fc9635781/uwp/uwp_main.cpp#L821) at `uwp_main.cpp`
must be called from UI thread.
but that will fix the crash only.

## Second
There is deadlock (I guess) happening at [this function](https://github.com/libretro/RetroArch/blob/8a6f7e6fffce7e9ea5bffcb24a4a797fc9635781/libretro-common/rthreads/rthreads.c#L501) in `rthreads.c`, 
it will freeze at black screen only..

### Stack call for this line

1. [void drivers_init](https://github.com/libretro/RetroArch/blob/8a6f7e6fffce7e9ea5bffcb24a4a797fc9635781/retroarch.c#L783)
2. [bool video_driver_init_internal](https://github.com/libretro/RetroArch/blob/8a6f7e6fffce7e9ea5bffcb24a4a797fc9635781/gfx/video_driver.c#L2848)
3. [bool video_thread_init](https://github.com/libretro/RetroArch/blob/8a6f7e6fffce7e9ea5bffcb24a4a797fc9635781/gfx/video_thread_wrapper.c#L680)
4. [void video_thread_wait_reply](https://github.com/libretro/RetroArch/blob/8a6f7e6fffce7e9ea5bffcb24a4a797fc9635781/gfx/video_thread_wrapper.c#LL76C37-L76C37)
5. [void scond_wait](https://github.com/libretro/RetroArch/blob/8a6f7e6fffce7e9ea5bffcb24a4a797fc9635781/libretro-common/rthreads/rthreads.c#L713)

```c
static void video_thread_wait_reply(thread_video_t *thr, thread_packet_t *pkt)
{
   slock_lock(thr->lock);

   while (pkt->type != thr->reply_cmd)
      scond_wait(thr->cond_cmd, thr->lock); //<--- It will stuck here..

   *pkt               = thr->cmd_data;
   thr->cmd_data.type = CMD_VIDEO_NONE;

   slock_unlock(thr->lock);
}
```

I have no idea how the threaded video works so wasn't able to fix this freeze.

**Comment by Nejsplitter** [comment]
I have found a workaround for this on series x, im on 1.15.0, what i do is i launch a flycast game, then bring up the retroarch menu, then navigate to retroarch video settings, output, and turn on threaded video, after this i can launch any core and it will retain threaded video, i have to do this process on every boot of retroarchbif i want threaded video for a core

**Comment by Nejsplitter** [comment]
I have found a workaround for this on series x, im on 1.15.0, what i do is i launch a flycast game, then bring up the retroarch menu, then navigate to retroarch video settings, output, and turn on threaded video, after this i can launch any core and it will retain threaded video, i have to do this process on every boot of retroarch if i want threaded video for a core

**Comment by greenchili2** [comment]
Really?  I tried it and as soon as I switch cores it changes back to off.  Although I do find it interesting that retroarch does not crash if you enable it while in the dreamcast core after a game has been started.

**Comment by Nejsplitter** [comment]
> Really? I tried it and as soon as I switch cores it changes back to off. Although I do find it interesting that retroarch does not crash if you enable it while in the dreamcast core after a game has been started.

i corrected my comment above, i should have mentioned i only tested with mupen angle core, the software cores all crash in my tests with this trick, bsnes, mesen, mgba, genesisplus etc, though i have no other hardware cores to test so i wonderf if someone could test this trick on other hardware cores and see if it works

**Comment by Nejsplitter** [comment]
Hi @basharast , threaded video can be activated without crashing/freezing on xbox series, this can be done by first launching a hardware core like flycast or duckstation then go into retroarch video settings and enable threaded video, do you have an idea what is happening in this context that allows threaded video to be enabled without crashing?

**Comment by Nejsplitter** [comment]
Hi @basharast , threaded video can be activated without crashing/freezing on xbox series, this can be done by first launching a hardware core like flycast or swanstation then go into retroarch video settings and enable threaded video, do you have an idea what is happening in this context that allows threaded video to be enabled without crashing?

**Comment by basharast** [comment]
> Hi @basharast , threaded video can be activated without crashing/freezing on xbox series, this can be done by first launching a hardware core like flycast or swanstation then go into retroarch video settings and enable threaded video, do you have an idea what is happening in this context that allows threaded video to be enabled without crashing?

Hi, sorry this part is beyond my understanding in `C` language, but as for the part that related to UWP as I mentioned above there is minor issue related to UI thread can be easily solved, when this part is fixed it will be easier for some one with better experience in `C` to solve the problem.

**Comment by TheElecPlay** [comment]
Unfortunately Threaded Video does indeed crash using MAME-current on Series X.
