### ISSUE TITLE
[Vulkan] Crash when closing content while a screenshot widget is still on-screen

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#14359]
## Description

With Vulkan set globally (meaning in `Settings > Drivers > Video`), while a game is loaded if you take a screenshot (F8 or `Quick Menu > Take Screenshot`) and exit the game before the screenshot widget disappears, RetroArch will crash.

I have 2 different GDB outputs: https://pastebin.com/71k3Y2ug and https://pastebin.com/R97fgGvi

### Expected behavior

Shouldn't crash.

### Actual behavior

It crashes.

### Steps to reproduce the bug

1. Set `Settings > Drivers > Video` to "Vulkan".
2. Start a game then take a screenshot.
3. Close content before the screenshot widget disappears, RA should crash (you may have to wait for the widget to disappear to get the crash).

### Bisect Results

Haven't bisected yet, already crashing with 1.9.0 tho. I know it's not very helpful but it doesn't crash with 1.8.0 so it seems to be an old regression.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.10.3 / ef0e9cc

### Environment information

- OS: Windows 10 (my Linux Mint VM doesn't support Vulkan so I can't test there)

**Comment by LibretroAdmin** [comment]
Is the GL driver still active while it tries to render stuff with the Vulkan display driver? Can you shed some more light on whether the gl or vulkan driver is initialized/setup when the crash happens?

**Comment by LibretroAdmin** [comment]
When do you get those Vulkan debug warnings? Can you list the exact steps to reproduce?

**Comment by bslenul** [comment]
I don't do anything special: with RA built with `VULKAN_DEBUG=1` I get these 2 messages in my MinGW window when I launch content, then the same 2 messages when I close content and finally the same 2 messages when closing RA:

https://user-images.githubusercontent.com/33353403/187307660-66745945-9a75-4984-b568-53d78c52ad7f.mp4

**Comment by LibretroAdmin** [comment]
@bslenul Can you re-test it now that a lot of thsee validation errors were fixed? I'd like to see new logs.

**Comment by bslenul** [comment]
OK, just tested with latest commit: without triggering the crash no more warnings/errors on launch game, on close content and when I exit RetroArch 👍 

However this is what I get when I trigger the crash:
```
VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x21a4ccc7990, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xe993b300000008bd, name = RetroArch image (437), type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x21a4ccc7990[], VkImage 0xe993b300000008bd[RetroArch image (437)] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
        [0] 0x21a4ccc7990, type: 3, name: NULL
        [1] 0xe993b300000008bd, type: 10, name: RetroArch image (437)
VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x21a4ccc7990, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xeb48f000000008be, name = RetroArch memory (918), type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x21a4ccc7990[], VkDeviceMemory 0xeb48f000000008be[RetroArch memory (918)] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
        [0] 0x21a4ccc7990, type: 3, name: NULL
        [1] 0xeb48f000000008be, type: 8, name: RetroArch memory (918)
VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x21a4ccc7990, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x820c3100000008bf, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x21a4ccc7990[], VkImageView 0x820c3100000008bf[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
        [0] 0x21a4ccc7990, type: 3, name: NULL
        [1] 0x820c3100000008bf, type: 14, name: NULL

```

**Comment by LibretroAdmin** [comment]
@bslenul can you retry again against master now that @sonninnos ’ PR has been merged?

**Comment by bslenul** [comment]
Still crashing :(

Output in terminal before log:
```
VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x28adc3f07c0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x2c9c290000000e81, name = RetroArch image (501), type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x28adc3f07c0[], VkImage 0x2c9c290000000e81[RetroArch image (501)] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
        [0] 0x28adc3f07c0, type: 3, name: NULL
        [1] 0x2c9c290000000e81, type: 10, name: RetroArch image (501)
[Thread 18268.0x3378 exited with code 0]
warning: VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x28adc3f07c0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x2c9c290000000e81, name = RetroArch image (501), type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x28adc3f07c0[], VkImage 0x2c9c290000000e81[RetroArch image (501)] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
       [0]  0x28adc3f07c0, type: 3, name: NULL
       [1]  0x2c9c290000000e81, type: 10, name: RetroArch image (501)
VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x28adc3f07c0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xa83b4a0000000e82, name = RetroArch memory (1014), type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x28adc3f07c0[], VkDeviceMemory 0xa83b4a0000000e82[RetroArch memory (1014)] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
        [0] 0x28adc3f07c0, type: 3, name: NULL
        [1] 0xa83b4a0000000e82, type: 8, name: RetroArch memory (1014)
warning: VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x28adc3f07c0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xa83b4a0000000e82, name = RetroArch memory (1014), type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x28adc3f07c0[], VkDeviceMemory 0xa83b4a0000000e82[RetroArch memory (1014)] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
       [0]  0x28adc3f07c0, type: 3, name: NULL
       [1]  0xa83b4a0000000e82, type: 8, name: RetroArch memory (1014)
VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x28adc3f07c0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x4f27db0000000e83, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x28adc3f07c0[], VkImageView 0x4f27db0000000e83[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
        [0] 0x28adc3f07c0, type: 3, name: NULL
        [1] 0x4f27db0000000e83, type: 14, name: NULL
warning: VUID-vkDestroyDevice-device-00378(ERROR / SPEC): msgNum: 1901072314 - Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x28adc3f07c0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x4f27db0000000e83, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x28adc3f07c0[], VkImageView 0x4f27db0000000e83[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
    Objects: 2
       [0]  0x28adc3f07c0, type: 3, name: NULL
       [1]  0x4f27db0000000e83, type: 14, name: NULL
```
There are also other validation errors in verbose logs: https://pastebin.com/gtchQtZ0
And GDB output: https://pastebin.com/ZuG1Qd3Q

**Comment by LibretroAdmin** [comment]
@bslenul Test if it still happens now

**Comment by bslenul** [comment]
No more crashes, as usual thank you so much sonninnos! 👍 

The VK validation errors are still insane in verbose logs but it has nothing to do with this issue.

Btw it built fine locally but the buildbot fails to build RA atm for Windows: https://git.libretro.com/libretro/RetroArch/-/jobs/2587616

**Comment by LibretroAdmin** [comment]
@bslenul Yeah I fixed the compilation errors in a followup commit, that was my bad.

@bslenul Can you open a new issue showing these Vulkan validation errors? Make a new Github issue with a new title.

**Comment by bslenul** [comment]
Done: #14484, *might* be a PCSX ReARMed only issue.
