### ISSUE TITLE
[3DS BUG]thumbnail list/playlist skipping

### ISSUE THREAD

**Issue by Trickygamers** [libretro/RetroArch#15708]
when thumbnails are enabled and are scrolling through the list when you tap it it will skip over one and same happens in the xmb menu when you scroll left or right looking through thre playlists it will skip over one.

**Comment by dmaglio** [comment]
same issue for me in PS Vita version, i use nightly version with xmb menu

**Comment by MrHuu** [comment]
Running into this same issue after finally updating my own builds. Only used RGUI.
It seems to be affected by the 'Menu Scroll Delay' option. 

```settings -> input -> menu controls -> menu scroll delay```

After increasing the delay threshold, i have it at ```512``` for now, most of the playlist entry skipping is fixed.

A guess, without addition research, is that a single frame when reading a playlist entry takes longer then the threshold. So the input is not cleared yet before the threshold is met.

**Comment by andresrrey** [comment]
I'm experiencing the same issue. I can confirm it is related to thumbnails. Adding start menu pictures and the boxart increased the number of skipped items, and they are always the ones missing images. This is not related to menu scroll delay, a value of 800 is still not solving the issue
