### ISSUE TITLE
The option "Filter by supported extensions" isn't showing up correctly

### ISSUE THREAD

**Issue by RockyGateway** [libretro/RetroArch#3576]
When you go to scan for games, the option "Filter by supported extensions" does not initially show up. To get it to show up to toggle it on or off, you must go to scan a directory, and below the option "Scan This Directory" you have to click on "No items.", then go to this directories parent directory for the option to finally show up.

**Comment by bparker06** [comment]
For me when I follow your instructions, the option to choose a directory goes away, but the filter option does appear at that point.

**Comment by bparker06** [comment]
I think what is happening is that when you go to scan for content, it wants you to choose a directory, so the filter option makes no sense then, because it's not showing you individual files anyways. But when you click inside an empty directory and go back, then it switches to trying to load a single file instead of a directory.

**Comment by fr500** [comment]
The problem seems to be when the dir is empty (or contains nothing of relevance with filter disabled)
The real solution is to show both "Parent Dir" and "Filter by supported extension" even if there are no items

**Comment by bparker06** [comment]
Commit 6826ec7 should fix this issue. The only thing is that 'filter unknown extensions' still will not show up when selecting only a directory, because the option does not make sense there, as you cannot see files anyway.

**Comment by twinaphex** [comment]
@RockyGateway Can we close this now or does bparker's commit not resolve your issue?

**Comment by RockyGateway** [comment]
I completely forgot to check, but doing it now, a few things are different (I'm using a nightly build, Oct 4th).

Even after scanning a directory and nothing showing up, the option does not appear, which may be intentional? Maybe I'm just not understanding that. It still only appears when I specifically press the option "No Items.". However, this time the option to scan is gone after being able to toggle unknown file extensions, and now nothing rom-related ever shows up in this scanning menu for me. Other things like video files I have on my HDD will be detected and listed without scanning, which is really odd.

**Comment by RockyGateway** [comment]
I just downloaded the latest nightly, December 8th 2016, and while the original "issue" still persists, the other problem I brought up is no longer an issue. Now when I enable the "Filter by supported extensions" option and go into a directory, everything is just there. No scanning required.

However, there still won't be anything that shows up in this scanning menu until I trigger this option to show up. It doesn't need to be enabled or disabled, just as long as it's showing up, roms and other files will show up in the directory I'm about to scan even without scanning first.
