### ISSUE TITLE
Can't load directly from archive with some cores

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#3632]
@bparker06 this seems related to the work you were doing.
Can't load directly from core with nestopia. Works fine with snes9x.

Tried only ZIPs, on Android and Windows.
Browsing the archive as folder and loading from within works.

Loading the zips from playlist works.

**Comment by fr500** [comment]
Reproduced with mgba now.

**Comment by fr500** [comment]
Loading games that I had loaded from history with nestopia and mgba fails too

**Comment by fr500** [comment]
Actually now I re-tested with snes9x, it "works" but it doesn't actually load the game, it ends up in a black screen.

**Comment by Awakened0** [comment]
Yeah, I was just getting the black screen in PCE_Fast and GPGX when loading single file zips with the latest nightly. The same games extracted work fine.

**Comment by escalade** [comment]
Confirmed for snes9x2010 zipped games. It works fine with 2294bcf so it must have been a commit after that. Getting a black screen, works fine if unzipped.

**Comment by bparker06** [comment]
Should be fixed with d493273 if you could test and let me know.

Thanks

**Comment by escalade** [comment]
Tested, and it works! Thanks :+1:

**Comment by Awakened0** [comment]
Yep, it's all good now.

**Comment by fr500** [comment]
Tested on Windows
Load Archive
- [ ] mgba (fullpath = false; block = false)
- [ ] nestopia (fullpath = false; block = false)
- [ ] snes9x (fullpath = false; block = false)
- [ ] fba (fullpath = true; block = true)


Browse Archive (zip) and Load
- [ ] mgba (fullpath = false; block = false)
- [ ] nestopia(fullpath = false; block = false)
- [ ] snes9x (fullpath = false; block = false)

**Comment by fr500** [comment]
On a sad note, load from archive is still broken on static linked platforms...
