### ISSUE TITLE
retroarch.exe stopped working (intel HD 3000)

### ISSUE THREAD

**Issue by eMSX** [libretro/RetroArch#4580]
Hello guys, i am having trouble with the latest version of Retroarch.

Retroarch 1.4.1 crashes directly when opened. 
Error message retroarch.exe stopped working.

Version 1.3.6 runs fine and reconizes the HD 3000 graphics drivers.
When i run 1.4.1 it crashes immediatly 

I am running Windows 10 home 64 bit. 
I have tested both the 32bit and the 64 bit versions, makes no difference.  
I am running it local, not using RDP.

The hardware is an Acer W700 tablet running Windows 10 home 1607 with all updates

Intel(R) Core(TM) i3-2375M CPU @ 1.50GHz
Intel HD Graphics 3000
Driver version 10.17.10.4229
Also tested with version 9.17.10.4229 same issue

Here is the debug log.

> > Intel(R) Core(TM) i3-2375M CPU @ 1.50GHz
> RetroArch [INFO] :: This is RetroArch version 1.4.1 (Git ba98ecd)
> RetroArch [INFO] :: === Build =======================================
> Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX
> Built: Feb 2 2017
> RetroArch [INFO] :: Version: 1.4.1
> RetroArch [INFO] :: Git: ba98ecd
> RetroArch [INFO] :: =================================================
> RetroArch [INFO] :: Loading default config.
> RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
> RetroArch [INFO] :: Redirecting save file to "C:\emulation\retro arch 1.41\saves.srm".
> RetroArch [INFO] :: Redirecting savestate to "C:\emulation\retro arch 1.41\states.state".
> RetroArch [INFO] :: Version of libretro API: 1
> RetroArch [INFO] :: Compiled against API: 1
> RetroArch [INFO] :: Set audio input rate to: 29970.03 Hz.
> RetroArch [INFO] :: Video @ 960x720
> RetroArch [INFO] :: Found GL context: wgl
> RetroArch [INFO] :: Detecting screen resolution 1920x1080.
> RetroArch [ERROR] :: [WGL]: wglCreateContextAttribsARB not supported.
> RetroArch [INFO] :: [GL]: Vendor: Microsoft Corporation, Renderer: GDI Generic.
> RetroArch [INFO] :: [GL]: Version: 1.1.0.

Here is the log of the working 1.3.6 on the same system.

> RetroArch [INFO] :: === Build =======================================
> Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX
> Built: Aug 4 2016
> RetroArch [INFO] :: Version: 1.3.6
> RetroArch [INFO] :: Git: 62281f8
> RetroArch [INFO] :: =================================================
> RetroArch [INFO] :: Config: loading config from: C:\emulation\retro arch 1.36\retroarch.cfg.
> RetroArch [INFO] :: Resetting undo buffers.
> RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
> RetroArch [INFO] :: Version of libretro API: 1
> RetroArch [INFO] :: Compiled against API: 1
> RetroArch [INFO] :: Set audio input rate to: 29975.00 Hz.
> RetroArch [INFO] :: Found shader "C:\emulation\retro arch 1.36\shaders\retroarch.cgp"
> RetroArch [INFO] :: Found shader "C:\emulation\retro arch 1.36\shaders\retroarch.glslp"
> RetroArch [INFO] :: Video @ 960x720
> RetroArch [INFO] :: Found GL context: wgl
> RetroArch [INFO] :: Detecting screen resolution 1920x1080.
> RetroArch [INFO] :: [WGL]: wglSwapInterval(1)
> RetroArch [INFO] :: [GL]: Vendor: Intel, Renderer: Intel(R) HD Graphics 3000.
> RetroArch [INFO] :: [GL]: Version: 3.1.0 - Build 9.17.10.4229.
> RetroArch [INFO] :: Querying GL extension: ARB_ES2_compatibility => doesn't exist
> RetroArch [INFO] :: Querying GL extension: ARB_sync => exists
> RetroArch [INFO] :: Querying GL extension: ARB_texture_float => exists
> RetroArch [INFO] :: Querying GL extension: EXT_texture_sRGB => exists
> RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_sRGB => exists
> RetroArch [INFO] :: [GL]: Supported extensions:

If more info is required  i am happy to help.

**Comment by fr500** [comment]
@eMSX the best bet would be a bisect. Can you build from source?

There were a few commits in december I think trying to determine GL capabilities on the fly.
Mentioning @twinaphex, @bparker06 and @loganmc10 since I think they may know what's up with this

**Comment by twinaphex** [comment]
I think the problem is on your end -

"RetroArch [INFO] :: [GL]: Vendor: Microsoft Corporation, Renderer: GDI Generic.
RetroArch [INFO] :: [GL]: Version: 1.1.0."

If it shows that then it means it can't find a REAL GL driver on your system and it instead resorts to a Microsoft-provided software rendered implementation of OpenGL, which utterly sucks. Don't even bother trying to use it, and find valid video drivers instead so that you can get a real GL driver for Windows.

**Comment by Brawl345** [comment]
Can confirm, have the same problem with Intel HD Graphics 3000. v1.3.6 works fine. I dunno how to get logs, retroarch_debug.exe also crashes on start (and I can't find any log files?). Setting
`menu_driver = "rgui"` in retroarch.cfg fixes it and uses the older GUI. My drivers are up-to-date and I'm on Windows 10 Pro 1607 64 bit.

**Comment by retro-wertz** [comment]
i can guess 2 reasons:
1. hd graphics 3000(sandy bridge) do not have official windows 10 drivers
2. retroarch 1.4.1 seems to have increase gl-feature requirements, #2 may
have only installed basic dx drivers but not full gl.

On Wed, Feb 8, 2017 at 12:55 AM, Andreas Bielawski <notifications@github.com

**Comment by eMSX** [comment]
I have also tried it on my Laptop an Acer V571G (also featuring a Sandy bridge cpu with GMA 300 HD. When i disable the Nvidia GPU it is giving the same error als the tablet. 

It is failing the reconize the Intel 3000 adapter. 
The drivers are the ones installed by Windows 10 by default. 
9.17.10.4229 on Windows 10 home 1607

Here 1.3.6 also works fine on the intergrated gpu.

**Comment by gouchi** [comment]
You may try [the latest driver version 9.17.10.4459](http://www.catalog.update.microsoft.com/Search.aspx?q=9.17.10.4459) available for Win10.

[Source](https://communities.intel.com/message/411353#411353)

**Comment by eMSX** [comment]
I have installed that driver but  Retro Arch still crashes directly  when started.

**Comment by Mohamed28** [comment]
I also did the installation and stillI have same issue.

**Comment by gouchi** [comment]
Can you try to install [Win8 driver](https://downloadcenter.intel.com/product/81500/Intel-HD-Graphics-3000) ?
Thank you.

**Comment by Mohamed28** [comment]
Man, install newer driver, older driver it's all same. This error persist.

**Comment by twinaphex** [comment]
I'd have to talk again to @loganmc10 to figure out the offending commit. It could be a case where once again it reports that it supports a specific extension but we should instead disable it, we ran into an issue before related to that and then the answer was 'disable it for all ATI cards on Windows'.

**Comment by loganmc10** [comment]
Has anyone narrowed it down to a specific commit?

**Comment by Mohamed28** [comment]
@loganmc10 There's anything I cany do? I am sorry, I am just a noob.

**Comment by bparker06** [comment]
Can someone with an affected system try [this](https://s3.amazonaws.com/retroarch/RetroArch-msvc2010-8e6df5f.exe) MSVC build and see if it works any different?

From the previous log, the line:

`RetroArch [ERROR] :: [WGL]: wglCreateContextAttribsARB not supported.`

is very peculiar since 1.3.6 also uses this function and it appears to work fine there. The entire reason for the crash is due to the failure to look up the pointer to that function in the OpenGL library. Since an OpenGL context cannot be created with the missing function, any further attempts to call a GL function will crash.

At first I would have also suspected a system driver issue, but I don't think this can be if 1.3.6 works.

**Comment by Mohamed28** [comment]
@bparker06, thank man, it does works but doesn't load any core and any game.

**Comment by bparker06** [comment]
Then I suspect the issue may be related to some GL code that gets compiled on msys2 builds that doesn't on msvc, like glslang or something.

**Comment by twinaphex** [comment]
You'll have to start bisecting. 

loganmc10 pushed through some extensions in RA that enable certain graphic features but this apparently was not properly tested against most common hardware as we can already see certain iGPUs no longer working on Windows.

GL is a mess like that.

BTW, I am very diplomatic right now for not calling out a certain somebody who felt it necessary to go on Reddit and cast a huge number of aspersions, but whatever, it's not been the first time I've had generosity shoved back in my face, so the dude can do what he feels like doing. I guess we'll just have to deal right now with an issue he indirectly caused in RetroArch right now and just suck it up. It's easy to cast criticism but it's not so easy to fix up your own mess now is it?

**Comment by loganmc10** [comment]
No one has even bisected this issue to prove that it was anything I changed. I don't have access to this kind of system so there is no way for me to test it. I someone provided any kind of backtrace or any useful debugging information I'd gladly fix it.

**Comment by twinaphex** [comment]
Look, I don't mind you dropping Glupen64, it's entirely up to you what you work on in your spare time and I am nobody's boss here. That is all fine and well. Criticism about the API too is fine, even though I disagree with the assessment that just because upstream is backwards and non-modular that this is supposedly libretro's fault. I reject that, but fine, people can have varying opinions on this and I am all for trying to find some common ground with upstream.

What I do have an issue with, though, is with a few choice things I saw you do over there on Reddit -

1 - Telling people that a Dolphin core is going to be a waste of time and being essentially very negative on it
2 - Telling people that 'oh Parallel was just one man's work, I think you are going to be sorely disappointed by its progress'. I think at that point you are just shitposting, sorry. It is not TinyTiger's problem or fault that you don't have any understanding about Vulkan or any deeper knowledge on the RDP so that you are unable to contribute to it, sorry. I have a very big issue with you disrespecting this guy's work, and the same with just shitposting about our Dolphin core.

That is what I wanted to get off my chest and I do think I needed to get that across to you. I did not appreciate those slights.

**Comment by bparker06** [comment]
This is not the place for such discussion, please take it elsewhere.

**Comment by bparker06** [comment]
@Mohamed28 The build I linked you to is 32-bit, so it will only load 32-bit cores.

Can you also try the [32-bit version](http://buildbot.libretro.com/nightly/windows/x86/2017-02-09_RetroArch.7z) of the current msys2 build and see if that works?

Until someone with the same/similar hardware, and the knowledge, time and patience to be able to bisect this comes forward, I don't think a whole lot of progress can be made, simply because we cannot reproduce it elsewhere.

**Comment by sm199** [comment]
@bparker06 version 1.4.1 x86 working fine...thnx man...
I tried latest nightly but with same error...

**Comment by bparker06** [comment]
@sm199 Were you trying an x86 nightly or was it an x86_64 one that didn't work? Trying to narrow down exactly what versions work and what doesn't.

**Comment by sm199** [comment]
@bparker06 i tried both versions...recently downloaded both versions but they are not working...

**Comment by bparker06** [comment]
So neither nightly works, and 1.4.1 x86 works, what about 1.4.1 x64? And have you tried the MSVC build I linked to? That one is more recent than 1.4.1 as well.

**Comment by sm199** [comment]
I tried your MSVC build so x86 version worked...before it was not working...
x64 build not working...xmb menu successfully opened but no cores are working because that exe belongs to x86...

**Comment by sm199** [comment]
Sorry for bad english...

**Comment by bparker06** [comment]
I found a machine here with an hd3000 and tried it myself, and it is working here: https://i.imgur.com/YdBYAZe.png

This is the latest 64-bit nightly also. Driver version is 9.17.10.2932 on Windows 7.

**Comment by sm199** [comment]
I don't know mine is intel hd 3000 or not...how to check it...???

**Comment by sm199** [comment]
I tried both latest nightly builds on windows 10 64 bit...with latest video driver installed...

**Comment by bparker06** [comment]
@sm199 Right click on the desktop -> Display settings -> Advanced display settings -> Display adapter properties

**Comment by sm199** [comment]
Okk i will check it and post screenshot here...

**Comment by Mohamed28** [comment]
@bparker06 I tested here, version 86x with your file works fine, the cores and games also worked. I used the yabause_libretro.dll to do the test.

**Comment by bparker06** [comment]
@Mohamed28 Are you saying the 32-bit MSVC build works or the 32-bit msys2 one works?

**Comment by eMSX** [comment]
I have also being testing. the 32 bit MSVC works perfect, the 32 bit msys2 gives the same eror.
Also the nightlys of 10-2 are giving the same error.

**Comment by sm199** [comment]
It is not showing anything about 3000.it is showing intel had graphics only....u can see screenshot here...
http://imgur.com/a/ivFe6

**Comment by hizzlekizzle** [comment]
@sm199 
HD3000 was the built-in IGP for the Sandy Bridge line of i-series CPUs. If you can look up what series your CPU came from, that should tell you.

**Comment by Mohamed28** [comment]
@bparker06 Yes man, actually I tried your file in both x86 and x86_64 in both it makes the GL works, but only in x86 runs cores and games.

**Comment by sm199** [comment]
@Mohamed28 did you try 32 bit msys2...???

**Comment by Mohamed28** [comment]
@sm199 Yes, I did sir, it's working.

**Comment by sm199** [comment]
U mean u tried latest nightly not v1.4.1,right...???

**Comment by Mohamed28** [comment]
@sm199 Yes, sir. The latest nightly from yesterday.

**Comment by sm199** [comment]
Okk now nightly is working fine for you but i am having the same error...only MSVC 32 bit build working fine... :(

**Comment by bparker06** [comment]
I have an automatic msvc build setup here:

[https://s3.amazonaws.com/retroarch/RetroArch-x86-msvc2005.exe](https://s3.amazonaws.com/retroarch/RetroArch-x86-msvc2005.exe)

Works on all Windows versions from 98 and up.

It rebuilds every hour if there's any code changes on the master branch. At least it is something until we can figure out what's going on with the msys2 builds.

**Comment by sm199** [comment]
Thanks @bparker06 but how to use it...??? Should i have to copy this in current nightly build...???

**Comment by bparker06** [comment]
You can run the exe by itself anywhere, or you can put it in an existing folder that you had from a nightly, sure.

**Comment by sm199** [comment]
So you mean all the nightly buids will work now...??? :D

**Comment by sm199** [comment]
And will i have to download it everytime when i will download latest nightly or upcoming stable build till it fixes...and thank you so much @bparker06 ...

**Comment by bparker06** [comment]
I don't quite follow what you're saying but, whenever you want a newer build you can just re-download that same exe, and keep it in the same folder, overwriting the old one. You don't have to re-download any actual nightly stuff from the buildbot, just my exe.

**Comment by fr500** [comment]
@eMSX can you just build from source?
it takes a while, and bisecting is a PITA I know, but it's the only way to get to the bottom of it.
Build guide
https://bot.libretro.com/docs/compilation/windows/

Once you can build you have to bisect
https://git-scm.com/docs/git-bisect

**Comment by eMSX** [comment]
I'm able to complile retroach, but i am experiencing some black blocks in front of the menu's. 

The bisecting doesn't go according to plan.

I am receiving some errors: 

$ git bisect bad
': is geen geldige naam: regel 88: export: 'dashless
Bisecting: 2949 revisions left to test after this (roughly 12 steps)
error: Your local changes to the following files would be overwritten by checkout:

but even if i say bisetct bad, is doesn't give me less revisions te test.

**Comment by bparker06** [comment]
That error is telling you that you have modified the source of the current commit you're on, so the bisect will not continue until you remove those changes.

**Comment by eMSX** [comment]
I have been bisecting till there isn't a single version left to test, with no luck, it still crashes directly after loading, while on my nvidia machine's it runs without issue. Even the 1.3.5 which i build crashes.

$ git bisect bad
7191465dcb038ce77991238a24e01bc91901cbfe is the first bad commit
commit 7191465dcb038ce77991238a24e01bc91901cbfe
Author: Mikael Brunnhede <mbrunnhede@hotmail.com>
Date:   Sun Jul 17 12:15:44 2016 +0200

    Fix bug in calculation of blocksize for savestates.

:040000 040000 0f8cef8d38a74224f54e36cbc31f971bab36059c e923966015f4721398342eea3f536d7901ff9fc6 M      managers

Has there been a change in the way retroarch is compiled since 1.3.6 ?

Please note that i am by no means a programmer, just a guy who read the above tutorials to compile his first program since "the game of life" in turbo pascal at school.

**Comment by bparker06** [comment]
@eMSX If the bisect is done correctly then the commit right before "the first bad" one should work. Can you confirm this?

**Comment by bparker06** [comment]
Also, how is it that you narrowed done a commit from July if 1.3.5 crashes too?

**Comment by Nickelbawker** [comment]
I have a intel3000-Windows10ProX64, with the issue here. Let me know if I can help test whatever is wrong. I changed video driver = d3d in the cfg and it doesn't have any graphics like PSP's XMB but the program opens up.

**Comment by bparker06** [comment]
This is a confirmed issue only on Windows 10. Other OpenGL programs besides RetroArch are having similar problems.
https://bugreports.qt.io/browse/QTBUG-42240

**Comment by sm199** [comment]
@bparker06 someone posted this WTFI.exe in retroarch forums.
https://github.com/alexey-lysiuk/tools/raw/master/wtfi/Release/wtfi.exe
It removes the Windows10 supportedOS GUID line from the xml manifest and now v1.5.0 working without any error.
https://forums.duke4.net/topic/8383-win10-hd3000-32bpp-crash-on-4897/

**Comment by bparker06** [comment]
Just FYI I have also added MSVC builds to the buildbot so it will create nightlies for it from now on:

http://bot.libretro.com/nightly/windows-msvc2010/

These should work fine without any changes on HD3000, and supports XP and up (the msys2 builds no longer support XP).

**Comment by Camui87** [comment]
First of all, thanks for your awesome work, Retroarch in generell and also all about this thread and to make Retroarch work again on Intel HD Graphics on Win 10.
Just a small thing I noticed about the MSVC2010 build: Retroachievements are missing, I loved that this feature was implemented, but was still a bit buggier in the 1.3.6 version which is working with HD3000. The new standard version on my other pc works fine now, but on that one I have to use the msvc2010 version, the achievements part is completely missing. Would it be possible to include this? :-)

Best regards!

**Comment by kingkork** [comment]
Sm199: can you advise how to use that wtfi.exe?  I used it with retroarch.exe as the target with no luck.

**Comment by kingkork** [comment]
I am having this same issue. New build. Msi motherboard with a GeForce gtx 1050 card with nvidia driver installed. Windows 10. I've downloaded the last few stable retro arch releases (starting with 1.5) and the last two nightlies. Although I have a 64bit OS I also tried x86 with the same results. Retroarch crashes at a white screen right upon load. The debug gives me the same output as OP. Would love any ideas or suggestions!

**Comment by fr500** [comment]
I already replied to you on reddit.
Your driver is the issue, that was something microsoft pushed 

> Weird... I have a GTX1080 and Win10 and it's working fine for me.
> 
> Try installing the drivers just in case http://www.geforce.com/drivers
> 
> Edit: https://forums.geforce.com/default/topic/992714/geforce-drivers/nvidia-display-21-21-13-7653-windows-update/
> 
> Maybe MS rolled a generic driver or something... again, install the NV drivers
>

**Comment by kingkork** [comment]
Thank you!  I'll try it tomorrow and report back.

**Comment by Microscoft** [comment]
I have come here from a YouTube channel called "Simply Austin". And he explained you can make ps1 look better with Beetle. And I have gotten the main menu to work, it just crashes when I try to play a game. Vulkan is not supported, GL crashes, and all other video drivers just give me a C++ runtime error. Has anyone found a fix for this issue?

**Comment by Brawl345** [comment]
Problem still exists in v1.6.0. Driver version is 9.17.10.4459 on Windows 10 1703 x64

**Comment by aidenn** [comment]
Hi,

It seems this is an issue with Intel's drivers and Windows 10. Intel isn't going to fix this, but a few kind souls hacked the drivers to think they're running on an older OS version here: https://github.com/LWJGL/lwjgl/issues/119

My path:
1. Installed 64-bit 4229 drivers from Intel - same as default W10 drive, OGl doesn't work at all.
2. Tried the patcher from the link above - didn't work at all.
3. Tried https://github.com/LWJGL/lwjgl/files/620292/Intel_OpenGL_Win10_9.17.10.4459_Fix_x64.zip - a different error in RetroArch
4. Tried https://github.com/LWJGL/lwjgl/files/661125/OpenGL_Fix_PHDGD_Omega_5.0.zip - RetroArch finally works (and other OGl stuff up to 3.1)

Where the files should go:

- x86 Systems
/System32/ig4icd32.dll
/System32/ig7icd32.dll

- x64 Systems
/System32/ig4icd64.dll
/System32/ig7icd64.dll
/SysWOW64/ig4icd32.dll
/SysWOW64/ig7icd32.dll

Everything on W10 Home 64-bit and SB 2500k.

**Comment by firewater2** [comment]
I have this problem on Windows 8, with both and old build and the latest one. My computer used to have a second AMD GPU, but it broke so now I'm stuck with an integrated Intel HD 4000. Should I follow the solution mentioned above?

**Comment by aidenn** [comment]
I think that solution is only for HD3000.

**Comment by RobLoach** [comment]
This should be fixed.

:stop_sign: Close.

**Comment by Xebozone** [comment]
I have strugged with this too...
Now I finally have RetroArch 1.7.0 working on my Intel HD2000
I followed what aidenn said by installing this:
https://github.com/LWJGL/lwjgl/files/661125/OpenGL_Fix_PHDGD_Omega_5.0.zip

However, I got the following:
C:\Users\Owner\AppData\Roaming\RetroArch>[INFO] RetroArch 1.7.0 (Git 4b68a21a7)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
Built: Dec 25 2017
[INFO] Version: 1.7.0
[INFO] Git: 4b68a21a7
[INFO] =================================================
[INFO] [Config]: Loading default config.
[INFO] [Config]: loading config from: (null).
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "C:\Users\Owner\AppData\Roaming\RetroArch\saves\.srm".
[INFO] Redirecting savestate to "C:\Users\Owner\AppData\Roaming\RetroArch\states\.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ 960x720
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 1440x900.
[ERROR] [WGL]: win32_set_video_mode failed.
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"
[ERROR] This core requires a content file.

I ran the Manifest updater (WTFI.exe) linked above and pointed it to Retroarch...
I then reverted the drivers back to the originals, but kept the ig7icd*.dll files as I didn't have those before.

C:\Users\Owner\AppData\Roaming\RetroArch>[INFO] RetroArch 1.7.0 (Git 4b68a21a7)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
Built: Dec 25 2017
[INFO] Version: 1.7.0
[INFO] Git: 4b68a21a7
[INFO] =================================================
[INFO] [Config]: Loading default config.
[INFO] [Config]: loading config from: (null).
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "C:\Users\Owner\AppData\Roaming\RetroArch\saves\.srm".
[INFO] Redirecting savestate to "C:\Users\Owner\AppData\Roaming\RetroArch\states\.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ 960x720
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 1440x900.
[INFO] [WGL]: wglSwapInterval(1)
[INFO] [GL]: Vendor: Intel, Renderer: Intel(R) HD Graphics 2000.
[INFO] [GL]: Version: 3.1.0 - Build 9.17.10.4459.
[INFO] [GL]: Using resolution 960x720
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: No errors.

**Comment by oltolm** [comment]
I have Windows 10 64-bit with an Intel i5-2500 with an Intel HD Graphics 2000. RetroArch 1.7.1 crashed on start. This [post](https://github.com/libretro/RetroArch/issues/4580#issuecomment-285960316) helped to fix the problem. I used [`wtfi`](https://github.com/alexey-lysiuk/tools/raw/master/wtfi/Release/wtfi.exe) to patch `retroarach.exe` and it started to work.

Apparently the Intel driver checks if you are running Windows 10 and actively prevents you from running OpenGL applications. They do it because Intel HD 2000 does not support Windows 10, in theory. In practice it work very well on Windows 10, or it would if Intel itself did not create problems on purpose.

Please add the solution to documentation, it was not easy not find it.

**Comment by Kikuchef** [comment]
Just about 2 hours ago i used the wtfi patch on the retroarach.exe im using the stable 1.7.1 windows 10 64 bit
![capture](https://user-images.githubusercontent.com/38059142/38285743-9e9dcf48-378f-11e8-8d77-d1dff1b087ea.PNG)

**Comment by Pat86** [comment]
Any chance this will be fixed officially? I still cant use Retroarch on my laptop. :(

**Comment by bparker06** [comment]
@Pat86 We cannot fix broken GPU drivers, and the other solutions that involve modifying the manifest are not acceptable for us to add for everyone. Unless you have some other ideas, all you can do currently is use either one of the d3d video drivers in RA, or gdi.

**Comment by Pat86** [comment]
@bparker06 patching the **retroarch.exe** with **wtfi** did the trick, thanks.

**Comment by fishcu** [comment]
I'm running into exactly the same problems/issues as @Xebozone described in the last comment in this thread.
My system is a Chromebox with an Intel HD 3000 iGPU.
I tried both with Windows 10 and now Windows 8.1, with exactly the same result. Because of BIOS issues, I cannot install & test Windows 7 unfortunately
**1.** Would running Windows 7 make a difference?

While I can boot RetroArch, I cannot launch Mupen64. Parallel works, but it has somewhat slower performance still, so I'd prefer to use Mupen64.
**2.** Any workarounds for running Mupen64 on Intel HD3000 and Windows (8, 10)?

This issue is so annoying, because Mupen64 runs just fine under Linux (Ubuntu, Lakka). The only reason I switched to Windows is to have better Xbox 360 wireless controller drivers...

**Comment by bparker06** [comment]
Did you try patching the driver with wtfi?

**Comment by fishcu** [comment]
My problem is that Mupen64 crashes; Retroarch works with Parallel currently.

I have followed @Xebozone 's steps (https://github.com/libretro/RetroArch/issues/4580#issuecomment-358012766) and have encountered the same successes, but also failures. Thus I am asking about Mupen64 finally.

If by "patching the driver" you mean running wtfi.exe on the `*.dll`s, that doesn't work.

Is there a way to get mupen64 running?
Would it run on Windows 7 instead of Windows 8.1 / Windows 10 that I'm currently using?

**Comment by bparker06** [comment]
@fishcu I believe mupen requires OpenGL 3.3 which your GPU probably doesn't support.

**Comment by fishcu** [comment]
I see. Any recommendations (emulators, plugins, settings) for the best compatibility and speed on my old toaster? I would like to run the likes of Mario Tennis 64, Majora's mask, Smash Bros., and the Mario Parties on it.

BTW, I had Mupen64 running inside retroarch under Ubuntu Linux, so definitely also lazy Intel is to blame for not supporting drivers a bit longer...

**Comment by 13ondy** [comment]
Hi Guys, I have a hp 8200  i7 2600 3.4ghz with 8gb of dd3ram, I have intel hd graphics, running windows 10 pro. The problem I'm having is when I open retroarch it goes to open then just shuts straight away, I tried the wtfi patch but it didn't seem to do anything, and retroarch is still doing the same thing opening then shutting straight away. Can anyone help me or give me some advice or other ideas of what I can do please.

**Comment by imagochan** [comment]
@eMSX have you tried downgrading windows 10 to windows 8.0? you could try it on your Acer W700tablet, download the drivers here: https://www.acer.com/us-en/support/drivers-and-manuals with your Serial Number/SNID or using the Acer Detection Utility: https://global-download.acer.com/SupportFiles/Files/SNID/APP/SerialNumberDetectionTool.exe 

After that you could try installing Retroarch, if it works well for you then maybe some generic driver is causing you trouble.

Here is the Windows 8.0 iso: https://archive.org/details/Windows8_201905
you can flash it with rufus.

**Comment by imagochan** [comment]
> Hi Guys, I have a hp 8200 i7 2600 3.4ghz with 8gb of dd3ram, I have intel hd graphics 2000, running windows 10 pro. The problem I'm having is when I open retroarch it goes to open then just shuts straight away, I tried the wtfi patch but it didn't seem to do anything, and retroarch is still doing the same thing opening then shutting straight away. Can anyone help me or give me some advice or other ideas of what I can do please.

try downgrading to Windows 8.0 and install OEM drivers to see if it makes any differene here is the link for downloading them: https://support.hp.com/us-en/drivers/selfservice/hp-compaq-8200-elite-small-form-factor-pc/5037931

Here is the Windows 8.0 iso: https://archive.org/details/Windows8_201905
you can flash it with rufus.

**Comment by imagochan** [comment]
> I see. Any recommendations (emulators, plugins, settings) for the best compatibility and speed on my old toaster? I would like to run the likes of Mario Tennis 64, Majora's mask, Smash Bros., and the Mario Parties on it.
> 
> Mario Tennis especially seems challenging, I could either get good graphics (framebuffer effects, etc.) but choppy, or full speed with lots of visual glitches.
> 
> BTW, I had Mupen64 running inside retroarch under Ubuntu Linux, so definitely also lazy Intel is to blame for not supporting drivers a bit longer...

https://emulation.gametechwiki.com/index.php/Nintendo_64_emulators here is a list with many emulators just for n64, try the recommended ones first.

**Comment by imagochan** [comment]
> @fishcu I believe mupen requires OpenGL 3.3 which your GPU probably doesn't support.

@fishcu can you check your openGL support here? https://www.realtech-vr.com/home/glview

**Comment by imagochan** [comment]
@eMSX this may be related to your problems https://community.acer.com/en/discussion/comment/621721

**Comment by LibretroAdmin** [comment]
No longer crashes: when Windows hands RetroArch the "GDI Generic" software OpenGL 1.1 renderer, the gl/glcore drivers now detect it, switch the video driver to gl1 and exit with a message instead of crashing.

The underlying cause is outside RetroArch: Intel never released a Windows 10 driver for HD 2000/3000, and Windows 10 widely reportedly hides its OpenGL driver from Windows 10-manifested applications, which leaves only the software renderer. On this hardware, use the d3d11, d3d10 or d3d9 video driver for hardware acceleration. Closing.
