### ISSUE TITLE
[Vita] No sound and can't see hidden folders on latest nighly builds

### ISSUE THREAD

**Issue by iamn0tdev** [libretro/RetroArch#4848]
Suddenly there is no sound on any core and can't see hidden folders. Show hiddens folder is enabled in the settings.

**Comment by frangarcj** [comment]
Do you know which is the latest nightly with sound?

**Comment by iamn0tdev** [comment]
16/04 or 17/04, I can't remember which one. Those builds aren't in libretro database anymore.

**Comment by frangarcj** [comment]
Sound should be fixed now 

https://github.com/libretro/RetroArch/commit/193b0b147fc59b9d41372a3b9da96722a74321c5

**Comment by iamn0tdev** [comment]
Thanks frangar. Sound is fixed (27/04) and hope you can fix the hidden folder issue. By the way I notice 28/04 and 29/04 builds have 38mb instead of 260mb. Have something else change?

**Comment by frangarcj** [comment]
Try again!!! :)

**Comment by frangarcj** [comment]
@iamn0tdev Should I close this?

**Comment by iamn0tdev** [comment]
@frangarcj no because the access to hidden folder is not fixed yet. Last build tested: 05/14/17

**Comment by meleu** [comment]
@iamn0tdev can you confirm if it's still happening?

**Comment by iamn0tdev** [comment]
@meleu its still happening. Last build tested: v1.7.5

**Comment by BombBloke** [comment]
Two points here:

The Vita uses FAT32/exFAT, which offers a hidden folder attribute. It uses said attribute on pretty much every bit of content it stores, so folders that Retroarch "sees" are in the minority. I guess Retroarch is thinking that only file/folder names that begin with a period are should be treated as hidden: this is not the case.

Even if the hidden attribute is manually removed from all content (eg with the "attrib" command from a PC), Retroarch still fails to show the *contents* of certain folders. For example, once unhidden, the pspemu folder can be seen and selected, but this leads to a "directory not found" message (as opposed to the "no items" message displayed when opening a regular empty folder). This disallows the storage of ROMs in an area where both Adrenaline and Retroarch can find them.

I guess folders such as pspemu are supposed to be sandboxed away from most Vita apps, though VitaShell can read/write to them without issue.
