### ISSUE TITLE
Can't move mouse or use keyboard after upgrage

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#5033]
## Description
no movement even after deleting the directory at ~/.config/retroarch and letting it be recreated
retroarch started with -v says this interesting thing:

RetroArch [WARN] :: [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?

and if i do ls:
ls -l /dev/input/event*
crw-rw---- 1 root input 13, 64 Jun  6 07:47 /dev/input/event0
crw-rw---- 1 root input 13, 65 Jun  6 07:47 /dev/input/event1
crw-rw---- 1 root input 13, 74 Jun  6 07:48 /dev/input/event10
crw-rw---- 1 root input 13, 75 Jun  6 07:48 /dev/input/event11
crw-rw---- 1 root input 13, 66 Jun  6 07:47 /dev/input/event2
crw-rw---- 1 root input 13, 67 Jun  6 07:47 /dev/input/event3
crw-rw---- 1 root input 13, 68 Jun  6 07:47 /dev/input/event4
crw-rw---- 1 root input 13, 69 Jun  6 07:47 /dev/input/event5
crw-rw---- 1 root input 13, 70 Jun  6 07:48 /dev/input/event6
crw-rw---- 1 root input 13, 71 Jun  6 07:48 /dev/input/event7
crw-rw---- 1 root input 13, 72 Jun  6 07:48 /dev/input/event8
crw-rw---- 1 root input 13, 73 Jun  6 07:48 /dev/input/event9

### Version/Commit
RetroArch version 1.6.0 (Git eee1ff7)

### Environment information
Linux AIVAS 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by retro-wertz** [comment]
should be similar to this https://github.com/libretro/RetroArch/issues/5016

**Comment by twinaphex** [comment]
@casdevel Seems we are getting more reports like this.

**Comment by i30817** [comment]
My keyboard and touchpad are from a 2008 portable, so i don't know if ps/2 has anything to do with it. I'll try to link a usb keyboard and see if something happens.

Nope, still doesn't work and has the same msg. However, alt-f4 to exit works (all the time) fortunately.

**Comment by i30817** [comment]
Worked around it by dropping to the config file and replacing the two instances of 'udev' for 'sdl' (aided by the names on the open pull request here).

**Comment by casdevel** [comment]
Question from log is answer.

@i30817 Visit link that @retro-wertz suggested or go [here](https://github.com/libretro/RetroArch/wiki/Input-drivers-in-Linux-without-Xorg) and follow instructions or change input driver to X11 (I think it's named "x").

@twinaphex There will probably be more issues like this if we don't change default input driver on Linux.

**Comment by RobLoach** [comment]
Confirmed on Ubuntu 16.04 [89fe5625](https://github.com/libretro/RetroArch/commit/89fe5625cbe14f9636b9cb65a7bb21f43137ba54). Keyboard has no affect on the menu. After RetroArch saves the config, it reports it's using the `udev` input driver.

**Comment by twinaphex** [comment]
@RobLoach Start doing a bisect.

**Comment by twinaphex** [comment]
@casdevel -  So all these issue are because we were previously using the x11 input driver by default, and now it tries to default to udev instead?

**Comment by twinaphex** [comment]
@casdevel How about if we just change 'x' to be the default input driver, even before udev? That way, if somebody manually chooses 'udev' as the input driver, it was at least their choice and they can still continue on using the x input driver by default as normal.

**Comment by twinaphex** [comment]
Pushed this -

https://github.com/libretro/RetroArch/commit/96bfb35e0b5dc16da586ffdb674ae042bb0bae3b

Set input_driver = "x" in your retroarch.cfg and tell me if everything is back to normal then.

The way it will work now is that x11 will be used before udev by default. You can still change it to udev inside Settings -> Driver.

**Comment by casdevel** [comment]
@twinaphex I doubt that anyone was actually using udev before #5010.

**Comment by bparker06** [comment]
@casdevel What about all the other context drivers that aren't X? Like DRM, Wayland etc.

**Comment by RobLoach** [comment]
Went through to find the afflicting commit.

1. Checked out https://github.com/libretro/RetroArch/commit/647dc488ffcd91d1f9a7da1c05518e9000fb1a32
2. Compiled
3. Ran and could move mouse/keyboard around
4. Checked out https://github.com/libretro/RetroArch/commit/a8f1831a62c82f2cb72d7e8b112d1ac7c7cf4e0f
5. Recompiled
6. Ran and could not move mouse/keyboard

So it seems like something in [Add multiple mice support](https://github.com/libretro/RetroArch/commit/a8f1831a62c82f2cb72d7e8b112d1ac7c7cf4e0f) affects this.

**Comment by twinaphex** [comment]
I pushed some commits -

What it does now is -

1) It will default to the x input driver on first startup instead of udev. This is for builds that have been compiled with both udev and X11 support.
2) IF we select the DRM/KMS context driver, because this is an X11-less context, if the x11 input driver is selected, we default to udev instead. If that is not available, we default to linuxraw instead.

Wayland context driver still uses its own Wayland input driver, so that continues to work fine.

**Comment by casdevel** [comment]
@bparker06 There may be few that still "don't allow" udev input driver, I will have to check sources again to be sure about that.

@RobLoach You are right, this is already discussed [here](https://github.com/libretro/RetroArch/issues/5016).

**Comment by casdevel** [comment]
@bparker06 DRM don't "force" input driver, Wayland prefers his own.

**Comment by casdevel** [comment]
@twinaphex I don't think that multiple mice support is possible on any input driver that uses OS windowing system API. For Windows I'm sure, for X11 I will have to check.

**Comment by sjnewbury** [comment]
@casdev [](https://en.wikipedia.org/wiki/Multi-Pointer_X)  It's a feature of the XInput2 API.

**Comment by casdevel** [comment]
@sjnewbury I'll check it out.

**Comment by sjnewbury** [comment]
@casdevel There seems to be something fundamental missing from all this:

The udev driver should work fine under X or Wayland for local input devices owned by the seat running the current session which haven't been claimed by the windowing system, and should still work even when it has been, although then there are arbitration issues.

RetroArch uses udev_device_new_from_syspath() which should return a udev_device object with access control to the device granted through logind/ConsoleKit.

As I understand it, access to an underlying device with libudev can either go through the /dev node if user/group access is permitted, or though a fd created on the fly with appropriate ACLs if granted by the udev authorization mechanism (logind/ConsoleKit).

Direct udev driver access to input devices such as joypads is VERY desirable, even when running under X due to the limitations of X input drivers such as force feedback/rumble support.  Hopefully, under Wayland there will soon be a well designed protocol suitable for gaming devices.

**Comment by casdevel** [comment]
@sjnewbury I'm not sure what you pointing out here. This was on setting up user permissions and that is solved.

**Comment by sjnewbury** [comment]
Point is, user permissions don't need to be set because libudev is given access to devices attached to the local seat on which the session is running.  This means remote logins do not get access to the resources, but any authorized local user can if the device is associated with the "seat" they are using; by default "seat0".  Multiple seats can be configured and used simultaneously with different devices attached GPUs/soundcards input devices, or whole USB hubs etc.  This could, for example be used to create a "seat" with just a GPU and joypad and have retroarch running standalone whilst allowing normal user logins on seat0.

**Comment by casdevel** [comment]
If you think that user permissions don't need to be changed, then you should post a solution.

**Comment by casdevel** [comment]
@twinaphex Regarding X11 input driver and multiple mice support, it should be possible.

I didn't tested anything, just done some reading and Xinput2 extension should make this possible. This functionality may be accessed with libxi library.

**Comment by RobLoach** [comment]
Just tested the lastest `master and `udev` is still not working on Ubuntu 16.04.

1. `rm ~/.config/retroarch/retroarch.cfg`
2. Start RetroArch
3. Quit
4. Update `~/.config/retroarch/retroarch.cfg` with `input_driver = "udev"`
5. Run RetroArch
6. Unable to move

Temporary work-around is to use `input_driver = "x"`

**Comment by casdevel** [comment]
I can't reproduce this issue (same steps, same OS).

Did you check log for udev error(s)?

**Comment by RobLoach** [comment]
RetroArch [WARN] :: [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?

**Comment by casdevel** [comment]
We already discussed how to solve permissions related issues.

**Comment by sjnewbury** [comment]
On Tue, 2017-06-20 at 15:51 -0700, Zoran Vuckovic wrote:
> We already discussed how to solve permissions related issues.
I don't think it this is a permissions related issue.  I gather the
current code doesn't now work with udev input devices under X, whereas
previously it did where permissions weren't a problem. [Because of
either logind or use of and "input" group policy.]


Whether it's appropriate to use the udev (driver) input devices under X
is another matter.  I can't see why it would be a problem though if the
devices in question have been explicitly excluded from use by the Xorg
driver.

Maybe I'm completely off here.

**Comment by casdevel** [comment]
@sjnewbury Why are permissions in play now and wasn't before should be clear if you start reading from top of this page (follow links too).

Whether changing permission for /dev/input/event is necessary you can find by compiling some simple program that reads/writes to/from one of these devices.

**Comment by sjnewbury** [comment]
@casdevel, except as I mentioned previously when you use libudev since it hands out a file descriptor if you have access to the /dev node OR authorisation through logind.

The simple program would have to utilise libudev.  I did exactly this btw, and it worked fine here without explicit /dev node permissions.

**Comment by casdevel** [comment]
@sjnewbury Like I said 8 days ago:

> If you think that user permissions don't need to be changed, then you should post a solution.

**Comment by sjnewbury** [comment]
On Wed, 2017-06-21 at 11:20 -0700, Zoran Vuckovic wrote:
> @sjnewbury Why are permissions in play now and wasn't before should
> be clear if you start reading from top of this page (follow links
> too).
> Whether changing permission for /dev/input/event is necessary you can
> find by compiling some simple program that reads/writes to/from one
> of these devices.
> 
But libudev isn't some simple program that accesses device nodes. 
Device nodes themselves are managed by udev.  libudev "talks" directly
to the udev daemon and negotiates access through other mechanisms like
logind and ConsoleKit.

I *did* write a simple program using libudev to test access to devices
which otherwise were not permitted through the device nodes, but were
allocated to "seat0" through loginctl, and it worked.

I don't *think* the problems people are seeing are due to permissions
but something that changed with respect to the udev driver when running
under X11.  I could be completely off-base, but I too have to manually
set the driver to X to get any input working despite my libudev test
program working, which is why I commented.

**Comment by parkerlreed** [comment]
Arch, up to date, fresh git compile with a clean config folder and udev is working fine. My user is in the "input" group if that makes a difference. 

Running in XFCE (so in X11)

**Comment by RobLoach** [comment]
Noting that this is still an issue with the udev input driver on Ubuntu 18.04.

```
[WARN] [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?
```

We've switched Linux's default input driver to be x, but it would be good to fix it up.

**Comment by orbea** [comment]
I can't reproduce this, but for those who can I would suggest looking into the system environment. Maybe it could be something with systemd permissions?

**Comment by i30817** [comment]
I changed to udev again and after adding my user to input things are sort of working. 

Except in kms (where libinput is not loaded because there is no compositor loaded so all of the touchpad quirks are not handled). In fact i changed back because i was trying to run retroarch in KMS which i found basically impossible without root except for pushing me to solve this problem.

Although, i don't think 'add your user to the input group' is a good solution to non-technical users.

**Comment by i30817** [comment]
I've seen repeated suggestions that this can be avoided by using libudev instead of accessing the linux device files directly (much like supposedly the device quirks can be used by using libinput).

**Comment by orbea** [comment]
> Although, i don't think 'add your user to the input group' is a good solution to non-technical users. 

Its a single command.
```
usermod -a -G input user_name
```
Then log out and log back in, type `groups` to ensure it worked.

While I agree it could be easier, I think there is nothing that can be done about it inside RetroArch other than documentation.

> I've seen repeated suggestions that this permission issue can be avoided by using libudev

I think we are already doing that?
```
$ ldd /usr/games/retroarch | grep udev
	libudev.so.1 => /lib64/libudev.so.1 (0x00007fa422a40000)
```
KMS also works fine with udev here.

Would it be possible to try a live environment for a distro without systemd to see if its any better with just eudev?

**Comment by i30817** [comment]
Eh, i should have mentioned 'libinput' instead of 'libudev'. AFAICT from internet information, the quirks are there. 

But sure, testing on a live cd is a good idea. I have no idea how the permission design is supposed to work on distros now and a mangled system from dozens of little config hacks isn't the best testbed. I want to suspect that desktop compositors don't add the user to the input group automagically now, like i assume they did before, and do something with systemd seats.

**Comment by bparker06** [comment]
@RobLoach Why don't you want to add yourself to the input group? This is completely normal and everyone else does it already, there is really no alternative besides making up a udev rule to change the group to something with a bit less permissions over other input devices, i.e. just for the pad(s) in question or something... but I think that's getting a bit silly.

**Comment by grant2258** [comment]
This is the way linux works for any lib to work the user would need to be in this group when running the lib. Im pretty lost at where all this is coming from

**Comment by grant2258** [comment]
also see https://github.com/libretro/RetroArch/issues/7748

**Comment by grant2258** [comment]
@bparker06 to you confused face udev mouse has been broken a long time it started working again here at this commit https://github.com/libretro/RetroArch/pull/7730

**Comment by i30817** [comment]
Yep, this is back again, after a stable flatpak update.

**Comment by i30817** [comment]
Yupppp. After installing "wayland-protocols" manually, the build RA is using a wayland context... and much faster to boot...

The flatpak "stable" update is just as slow though. Fix the buildbots!

**Comment by orbea** [comment]
You need at least wayland-protocols-1.1.5.

**Comment by i30817** [comment]
Opened a issue https://github.com/flathub/org.libretro.RetroArch/issues/101

**Comment by realnc** [comment]
I'm not using wayland, just good old X11, butI have the same issue. udev doesn't work, neither for keyboard nor gamepad. It just prints the usual "check permissions" warning. My user *is* in the `input` group, which is the group the `/dev/input/` files belong to.

The RetroArch documentation says that udev is the most full-featured input driver for gamepads, which is why I want to use it.

I installed RetroArch through flatpak (from flathub) on Gentoo Linux. Latest version:

```
org.libretro.RetroArch             x86_64       stable      flathub
```

**Comment by realnc** [comment]
Solved for me by running the flatpak RA binary outside of flatpak. See: https://github.com/libretro/RetroArch/issues/4664#issuecomment-510340394

**Comment by etheling** [comment]
I had a  `RetroArch [WARN] :: [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?` problem that was related to no access to under `/run/udev/data/...` (used 'strace retroarch.. | grep udev'  to nail it down).

This is probably a very, very corner case but may be relevant to consider if using RetroArch from a container or with some other isolation mechanism that may block access to devices/files.

**Comment by twinaphex** [comment]
Can someone check if this PR -

https://github.com/libretro/RetroArch/pull/12830

resolves the issue?

**Comment by i30817** [comment]
Is that after or before b2c87baa87 ? I just tried my self compiled build here, and the problem remains.

In x11, RA master compiled with:
`./configure --disable-discord --disable-qt --disable-cdrom --enable-x11 --disable-caca --disable-sdl --disable-sdl2 --disable-opengl1 --disable-ffmpeg --disable-flac --disable-wayland --disable-kms --enable-opengl --enable-vulkan && make -j2 DEBUG=0 GL_DEBUG=0 TARGET=retroarch_x11;`

user not in the audio group, complete list: `myusername adm cdrom sudo dip plugdev lpadmin lxd sambashare`

then trying the udev driver on this build has no key input on restart and the message:
`[WARN] [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?`

Iirc, if i was on wayland and built the wayland version instead of x11, udev would work fine.

**Comment by i30817** [comment]
Wait i saw when it was posted, not when it was merged.

Let me compile and get back to you.

**Comment by grant2258** [comment]
Just looking for some clarification here I see a lot of "modern" way comments. If your using wayland there is a wayland driver if your using x there is and x driver. These are the drivers that need fixed and that should be selected by the video driver. Is the general idea that the other drvers be dropped and just use libudev ? libudev is part is systemd  what if systemd isint on the distro what exactly is the modern solution for all systems to be supported.

**Comment by v-fox** [comment]
> Just looking for some clarification here I see a lot of "modern" way comments. If your using wayland there is a wayland driver if your using x there is and x driver. These are the drivers that need fixed and that should be selected by the video driver. Is the general idea that the other drvers be dropped and just use libudev ? libudev is part is systemd what if systemd isint on the distro what exactly is the modern solution for all systems to be supported.

I'm quite baffled by this "udev=systemd" misconception, pretty sure that udev existed way before systemd (like 7 years). Maybe because later systemd project "ate it up" (non-systemd distros would still run udev fork). But even if you're concerned about marginal non-systemd distros out there, first you'll need to fix things up for the majority of users anyway.

libudev is for general controlled device access to their raw interfaces (instead of permanent full access). From what I've heard, under wayland it's preferred to use libinput for input devices but that's because of "preprocessed"/middleware API instead of raw (libevdev ?) or a X-based one (libxcb ?). Kind of using SDL's input API but more Linux-centric / less generic, I guess. For such I/O-sensitive app like RA it would likely be better to be as close to raw interfaces as possible.

**Comment by grant2258** [comment]
It's clear systemd ate libudev I'm just nor sure if it will function  as intended outwith systemsd. iif it does that will be fine  the biggest issues with x and wayland drivers as far as input goes is multiple mice. I know it can be done in x not sure about wayland haven't even looked at that much to be honest right now both drivers attach every mouse device to the act as the same mouse. As far as the issue goes the distribution should be setting the users groups properly if not the user would need to do it.

**Comment by v-fox** [comment]
> As far as the issue goes the distribution should be setting the users groups properly if not the user would need to do it.

I will repeat again: distributions have set groups correctly (there aren't supposed to be any groups other than 'users'). As in: YOU ARE NOT INTENDED TO HAVE DIRECT PERMANENT ACCESS TO DEVICES EVER ! STOP doing it, STOP encouraging it ! This is not year 2005. Fix your access requests instead.

**Comment by grant2258** [comment]
Linux mint latest sets the input groups I think your over generalising here

**Comment by v-fox** [comment]
> Linux mint latest sets the input groups as do others I think your over generalising here.

I've launched latest install image on VM and it says:
```
mint@mint:~$ groups
mint adm cdrom sudo dip plugdev lpadmin sambashare
```
All pretty much for legacy printing services without proper access control and "just in case" default samba config, cdrom (for burning commands) that no one has anymore.

/dev/input devices have 'input' group that user, intentionally, does not have. And should not have.

> I've never seen a disto with one group in it. There are groups for Audio input video on many distributions.

How about openSUSE ?
```
fox@arsenal (13:15:27) [ ~ ] % groups
users wheel
```
And the wheel I added myself to avoid punching root password for editing some root-only config files.

> Can you point out a source that's definitive that so many distros got it wrong I do stand to be corrected in a none wayland context.

How about you point me to "so many distros" that give every user full permanent I/O access by default, which makes them snoop on each other without any protection, instead ? Since you're the one who, apparently, missed more than a decade of Linux desktop developments.

**Comment by grant2258** [comment]
Well latest mint added the input group for me never added it myself. As did manjaro.

**Comment by gouchi** [comment]
So how can we advance for this issue ?

I found some code in this [page](https://www.freedesktop.org/wiki/Software/systemd/multiseat/)  related to udev and seat. Could it help to improve the udev driver ? If somebody wants to test 
```
gcc -o udev-list udev-seat.c `pkg-config --cflags --libs libudev`
```

```
#include <libudev.h>
#include <linux/types.h>
#include <linux/input.h>
#include <linux/kd.h>
#include <stdio.h>
#include <string.h>

int enum_input_on_seat(const char* seat)
{
    struct udev* udev;
    struct udev_enumerate* enumerate;
    struct udev_list_entry *item, *first;

    if (!seat)          /* ← Here's the beef */
        seat = "seat0"; /* ← Here's the beef */

    udev = udev_new();

    enumerate = udev_enumerate_new(udev);
    udev_enumerate_add_match_subsystem(enumerate, "input");

    if (strcmp(seat, "seat0") != 0)                    /* ← Here's the beef */
        udev_enumerate_add_match_tag(enumerate, seat); /* ← Here's the beef */

    udev_enumerate_scan_devices(enumerate);

    first = udev_enumerate_get_list_entry(enumerate);
    udev_list_entry_foreach(item, first)
    {
        struct udev_device* d;
        const char* d_seat;

        d = udev_device_new_from_syspath(udev, udev_list_entry_get_name(item));

        d_seat = udev_device_get_property_value(d, "ID_SEAT"); /* ← Here's the beef */
        if (!d_seat)                                           /* ← Here's the beef */
            d_seat = "seat0";                                  /* ← Here's the beef */

        if (strcmp(seat, d_seat) == 0) { /* ← Here's the beef */

            /* Found a device, yihaaa! */
            printf("Found device %s\n", udev_device_get_devnode(d));

            /* do_something_with_our_input_device(d); */
        }

        udev_device_unref(d);
    }

    udev_enumerate_unref(enumerate);
    udev_unref(udev);
    return 0;
}
int main() {
     return enum_input_on_seat("seat0");
}
```

**Comment by i30817** [comment]
I want to mention something here. I remember having either behavior with my previous computer touchpad in scummvm in a KMS build of retroarch.

One, but not only, of the problems was 'right click' not existing.

Turns out that several of the 'synaptic quirks' that were previously installed by /usr/share/x11/xorg.conf.d/*synaptics-quirks.conf  were moved to libinput for wayland.

So there are costs to 'direct access' namely you're losing all the 'oh shit this hardware has inane bugs or tricky configuration and there are thousands of variations, better stuff all this crap on a database' kind of stuff.

I haven't tried scummvm again in RA to see if things are better in my new portable. Could be, could also not be, because it's one of those portables where the 'touchpad buttons' are zones of the touchpad, not actual buttons.

**Comment by grant2258** [comment]
@gouchi from an terminal in x I get same with a normal tty

Found device (null)
Found device /dev/input/event1
Found device (null)
Found device /dev/input/event0
Found device (null)
Found device /dev/input/event5
Found device (null)
Found device /dev/input/event6
Found device (null)
Found device /dev/input/event7
Found device (null)
Found device /dev/input/event8
Found device (null)
Found device /dev/input/event9
Found device (null)
Found device /dev/input/event10
Found device (null)
Found device /dev/input/event2
Found device (null)
Found device /dev/input/event3
Found device /dev/input/mouse0
Found device (null)
Found device /dev/input/event11
Found device (null)
Found device /dev/input/event12
Found device (null)
Found device /dev/input/event13
Found device (null)
Found device /dev/input/event14
Found device (null)
Found device /dev/input/event15
Found device (null)
Found device /dev/input/event16
Found device (null)
Found device /dev/input/event17
Found device (null)
Found device /dev/input/event18
Found device (null)
Found device /dev/input/event4
Found device /dev/input/mice

**Comment by i30817** [comment]
Found device (null)
Found device /dev/input/event2
Found device (null)
Found device /dev/input/event8
Found device (null)
Found device /dev/input/event9
Found device (null)
Found device /dev/input/event1
Found device (null)
Found device /dev/input/event0
Found device (null)
Found device /dev/input/event10
Found device (null)
Found device /dev/input/event11
Found device (null)
Found device /dev/input/event12
Found device (null)
Found device /dev/input/event13
Found device (null)
Found device /dev/input/event14
Found device (null)
Found device /dev/input/event15
Found device (null)
Found device /dev/input/event16
Found device (null)
Found device /dev/input/event17
Found device (null)
Found device /dev/input/event3
Found device (null)
Found device /dev/input/event4
Found device /dev/input/mouse0
Found device (null)
Found device /dev/input/event6
Found device /dev/input/js0
Found device (null)
Found device /dev/input/event5
Found device (null)
Found device /dev/input/event7
Found device /dev/input/mice

**Comment by grant2258** [comment]
ive done a bit of testing nothing kms yet but ive added some code to filter out the mouse and keyboard from the example code and all seems good. Im not sure how we would deal with hotplug in this scenario though.

**Comment by grant2258** [comment]
here is some test cope to see if it makes a difference to anyone having these issues 
[test.zip](https://github.com/libretro/RetroArch/files/7110103/test.zip) just put it in your source dir then git apply test.patch let me know good or bad if anyone tests it.

**Comment by grant2258** [comment]
here is some test cope to see if it makes a difference to anyone having these issues 
[test.zip](https://github.com/libretro/RetroArch/files/7110103/test.zip) just put it in your source dir then git apply test.patch let me know good or bad if anyone tests it. Im still getting WARN] [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*? when no in the input group but that could be the the way we are accessing things beyond the opening

**Comment by i30817** [comment]
Guess this is never going to get fixed:

udev driver (in kms, x, or wayland): works on wayland, by inheriting the 'seat' with the right permissions set by policykit at login, or adding the user to the 'input' group in distros where it's not added because security implications (keyloggers etc).
On x or kms does not work, seat is not being inherited on login.


The other udev kms problem of libinput never actually being loaded and the quirks not being active: no solution as far as i can tell. Probably would require retroarch kms depending on a library that loads libinput on login or loading and using libinput directly? I dunno.

**Comment by sjnewbury** [comment]
@i30817, having a libinput driver for kms/console would probably be a good idea.  It shouldn't be too difficult to implement either.

There unfortunately isn't really a good comprehensive framework for all this.  Unlike in Windows where all input devices are accessible both through a high level and low level API, because Linux has always had multiple input APIs even only considering X11 with 4 different input subsystems, there isn't any standard.  Wayland hoped to address this but piping low latency input through the wayland protocol isn't really viable, so it was put onto the back-burner since keyboard and pointer devices worked well enough*.  There were proposals for a gaming input protocol which would just arbitrate an input device then set up a file descriptor and get out of the way.  I think this hasn't happened is mostly because using udev/evdev works if you can mangle the permissions and make sure nothing else is using the device!

Google actually implemented a gaming-input extension: https://lists.freedesktop.org/archives/wayland-devel/2017-January/032697.html but this was limited to presenting a simple gamepad which mapped to the HTML5 Gamepad API.

*pointer support for containment and relative mouse came with later protocol extensions.  Does this work well enough for serious gamers?  I'm actually interested to know, it's certainly okay for causal use, but I have my doubts for e-sports.

**Comment by i30817** [comment]
I realized something interesting about this.

Currently i'm running Gnome on X, and previously i was running Gnome on Wayland (ubuntu backtracked).

On Gnome on X the x driver works on a tty KMS and Gnome, on Gnome on Wayland, the udev driver works on a tty KMS and on Gnome. (with two retroarch compiles, one for KMS and another for X).

So you basically just need to use either 'always x' or 'always udev'.

I'm not sure if it would work for a combined RA build that tried to build both the KMS/Wayland support and the X11 support.

**Comment by i30817** [comment]
I found this comment on how to force nvidia to start in vulkan KMS but i'm not quite sure it's a good idea:

https://github.com/libretro/RetroArch/issues/5414#issuecomment-450495282

**Comment by parkerlreed** [comment]
Strange. Both udev and x are working on Arch with KMS/DRM.

Is there any more output if you run RetroArch with verbosity increased?

**Comment by i30817** [comment]
Probably, but I'm not able to test things since the computer that exhibited this is long long gone.

**Comment by ewtoombs** [comment]
I just checked in Archlinux, and it worked after I added myself to the input group.
I can try it again in alpine linux at my earliest convenience.
That was the distro that it failed with.

**Comment by gouchi** [comment]
Hi @i30817,

I think the issue can be closed.

I could not reproduce the issue. I made a test on [Manjaro live KDE Plasma](https://download.manjaro.org/kde/25.0.8/manjaro-kde-25.0.8-250902-linux612.iso).

```
id
uid=1000(manjaro) gid=1000(manjaro) groups=1000(manjaro),3(sys),90(network),98(power),991(lp),998(wheel)
```

I installed [game-devices-udev](https://codeberg.org/fabiscafe/game-devices-udev#how-to-set-it-up) for the gamepad which relies on [uaccess tag](https://wiki.archlinux.org/title/Udev#Allowing_regular_users_to_use_devices).

I compile latest RA [b73d764](https://github.com/libretro/RetroArch/tree/b73d76445f67744e1201176d0cde06fe6257cc2f) with

```
git clone https://github.com/libretro/retroarch
cd retroarch
./configure --disable-qt --disable-x11 --disable-wayland --disable-pipewire --enable-kms --enable-egl --enable-vulkan
./retroarch -v 
```
Of course, I stopped sddm before launching RA using `sudo systemctl stop sddm.service` in the terminal ;)

<details>
  <summary>retroarch --features</summary>

```
Features:
  LibretroDB      - LibretroDB support: yes
  Command         - Command interface support: yes
  Network Command - Network Command interface support: yes
  SDL2            - SDL2 input/audio/video drivers: yes
  UDEV            - UDEV/EVDEV input driver: yes
  Threads         - Threading support: yes
  Vulkan          - Video driver: yes
  OpenGL          - Video driver: yes
  EGL             - Video context driver: yes
  KMS             - Video context driver: yes
  ALSA            - Audio driver: yes
  OSS             - Audio driver: yes
  Jack            - Audio driver: yes
  PulseAudio      - Audio driver: yes
  7zip            - 7zip extraction support: yes
  zlib            - zip extraction support: yes
  External        - External filter and plugin support: yes
  GLSL            - Fragment/vertex shader driver: yes
  glslang         - Fragment/vertex shader driver: yes
  rpng            - PNG image loading/encoding: yes
  rjpeg           - JPEG image loading: yes
  Dynamic         - Dynamic run-time loading of libretro library: yes
  FFmpeg          - On-the-fly recording of gameplay with libavcodec: yes
  FreeType        - TTF font rendering driver: yes
  Netplay         - Peer-to-peer netplay: yes
  SSL             - SSL Support: yes
  Video4Linux2    - Camera driver: yes
```

</details> 

<details>
  <summary>RA log</summary>

```
INFO] [Config] Looking for config in: "/home/manjaro/.config/retroarch/retroarch.cfg".
[INFO] RetroArch 1.21.0 (Git b73d76445f)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.21.0
[INFO] Git: b73d76445f
[INFO] Built: Sep 21 2025
[INFO] =================================================
[INFO] [Input] Found input driver: "linuxraw".
[INFO] [Environ] SET_PIXEL_FORMAT: RGB565.
[INFO] [Core] Version of libretro API: 1, Compiled against API: 1
[INFO] [Core] Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[INFO] [Video] Set video size to: 960x720.
[INFO] [DRM] Found 5 connectors.
[INFO] [DRM] Connector 0 connected: no
[INFO] [DRM] Connector 0 has 0 modes.
[INFO] [DRM] Connector 1 connected: yes
[INFO] [DRM] Connector 1 has 24 modes.
[INFO] [DRM] Connector 1 assigned to monitor index: #1.
[INFO] [DRM] Connector 2 connected: no
[INFO] [DRM] Connector 2 has 0 modes.
[INFO] [DRM] Connector 3 connected: no
[INFO] [DRM] Connector 3 has 0 modes.
[INFO] [DRM] Connector 4 connected: no
[INFO] [DRM] Connector 4 has 0 modes.
[INFO] [DRM] Mode 0: (1920x1080) 1920 x 1080, 60.000000 Hz
[INFO] [DRM] Mode 1: (1920x1080) 1920 x 1080, 74.972504 Hz
[INFO] [DRM] Mode 2: (1920x1080) 1920 x 1080, 59.939392 Hz
[INFO] [DRM] Mode 3: (1920x1080) 1920 x 1080, 50.000000 Hz
[INFO] [DRM] Mode 4: (1600x1200) 1600 x 1200, 60.000000 Hz
[INFO] [DRM] Mode 5: (1680x1050) 1680 x 1050, 59.954250 Hz
[INFO] [DRM] Mode 6: (1280x1024) 1280 x 1024, 75.024673 Hz
[INFO] [DRM] Mode 7: (1280x1024) 1280 x 1024, 60.019741 Hz
[INFO] [DRM] Mode 8: (1440x900) 1440 x 900, 74.984428 Hz
[INFO] [DRM] Mode 9: (1440x900) 1440 x 900, 59.887444 Hz
[INFO] [DRM] Mode 10: (1280x960) 1280 x 960, 60.000000 Hz
[INFO] [DRM] Mode 11: (1280x720) 1280 x 720, 60.000000 Hz
[INFO] [DRM] Mode 12: (1280x720) 1280 x 720, 59.943436 Hz
[INFO] [DRM] Mode 13: (1280x720) 1280 x 720, 50.000000 Hz
[INFO] [DRM] Mode 14: (1152x720) 1152 x 720, 60.000854 Hz
[INFO] [DRM] Mode 15: (1024x768) 1024 x 768, 75.028580 Hz
[INFO] [DRM] Mode 16: (1024x768) 1024 x 768, 60.003841 Hz
[INFO] [DRM] Mode 17: (800x600) 800 x 600, 75.000000 Hz
[INFO] [DRM] Mode 18: (800x600) 800 x 600, 60.316540 Hz
[INFO] [DRM] Mode 19: (720x576) 720 x 576, 50.000000 Hz
[INFO] [DRM] Mode 20: (720x480) 720 x 480, 59.940060 Hz
[INFO] [DRM] Mode 21: (640x480) 640 x 480, 75.000000 Hz
[INFO] [DRM] Mode 22: (640x480) 640 x 480, 59.940475 Hz
[INFO] [DRM] Mode 23: (640x480) 640 x 480, 59.928570 Hz
[INFO] [GL] Found GL context: "kms".
[INFO] [GL] Detecting screen resolution: 1920x1080.
[WARN] [KMS] Falling back to mode 0 (default).
[INFO] [EGL] Found EGL client version >= 1.5, trying eglGetPlatformDisplay.
[INFO] [EGL] EGL version: 1.5.
[INFO] [EGL] Current context: 0x55c5045ed891.
[INFO] [KMS] New FB: 1920x1080 (stride: 7680).
[INFO] [GL] Vendor: NVIDIA Corporation, Renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2.
[INFO] [GL] Version: 4.6.0 NVIDIA 575.64.05.
[INFO] [GL] Using resolution 1920x1080.
[INFO] [GL] Default shader backend found: glsl.
[INFO] [GL] Using GLSL shader backend.
[INFO] [GLSL] Checking GLSL shader support...
[WARN] [GLSL] Stock GLSL shaders will be used.
[INFO] [GLSL] Found GLSL vertex shader.
[INFO] [GLSL] Found GLSL fragment shader.
[INFO] [GLSL] Linking GLSL program.
[INFO] [GLSL] Found GLSL vertex shader.
[INFO] [GLSL] Found GLSL fragment shader.
[INFO] [GLSL] Linking GLSL program.
[INFO] [GLSL] Found GLSL vertex shader.
[INFO] [GLSL] Found GLSL fragment shader.
[INFO] [GLSL] Linking GLSL program.
[INFO] [GL] Using 4 textures.
[INFO] [GL] Loaded 1 program(s).
[INFO] [GL] Using GL_RGB565 for texture uploads.
[INFO] [Video] Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev] Pad #0 (/dev/input/event25) supports force feedback.
[INFO] [udev] Pad #0 (/dev/input/event25) supports 16 force feedback effects.
[INFO] [Autoconf] Xbox 360 Controller configured in port 1.
[INFO] [Input] Found joypad driver: "udev".
[INFO] [Video] Found display server: "kms".
[INFO] [Audio] Set audio input rate to: 48000.00 Hz.
[INFO] [PulseAudio] Requested 24576 bytes buffer, got 18432.
[INFO] [Audio] Started synchronous audio driver.
[INFO] [ALSA] Using ALSA version 1.2.14
[INFO] [Microphone] Initialized microphone driver.
[INFO] [Display] Found display driver: "gl".
[INFO] [Playlist] Loading favorites file: "/home/manjaro/.config/retroarch/playlists/builtin/content_favorites.lpl".
[INFO] [Playlist] Loading history file: "/home/manjaro/.config/retroarch/playlists/builtin/content_history.lpl".
[INFO] [Playlist] Loading history file: "/home/manjaro/.config/retroarch/playlists/builtin/content_image_history.lpl".
[INFO] [Playlist] Loading history file: "/home/manjaro/.config/retroarch/playlists/builtin/content_music_history.lpl".
[INFO] [Playlist] Loading history file: "/home/manjaro/.config/retroarch/playlists/builtin/content_video_history.lpl".
[INFO] [KMS] New FB: 1920x1080 (stride: 7680).
[INFO] [KMS] New FB: 1920x1080 (stride: 7680).
[INFO] [Config] Saved config to "/home/manjaro/.config/retroarch/retroarch.cfg".
[INFO] [Core] Unloading core...
[INFO] [Core] Unloading core symbols...
```

</details>

**Comment by gouchi** [comment]
@hizzlekizzle I think this issue could be closed.

**Comment by LibretroAdmin** [comment]
@i30817 
Try to see if this addresses it somewhat
https://github.com/libretro/RetroArch/commit/fb621f2e1239fa8daee02da87a8e20f52678fc6c

**Comment by i30817** [comment]
I don't even have a desktop linux computer anymore. I can't test it. I also think this should be closed. Its too old to think things haven't changed and another person with the same problem should open it if it still exists (which I doubt).
