### ISSUE TITLE
PS Vita TV: any network operation takes too long time

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#6147]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

PS Vita TV: any network operation takes too long time

### Expected behavior

I expected download speed at least 300-500 KB/s

### Actual behavior

Zip archive which contains core info files was downloading near 1 minute.

### Steps to reproduce the bug

1. Go to Updater
2. Click "Update Core Info Files"
3. profit

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1dc918b

### Environment information

- OS: PS Vita TV 3.60 Henkaku 10 + Enzo
- Compiler: [In case you are running local builds]

**Comment by bparker06** [comment]
#6127 probably related.

**Comment by meleu** [comment]
@ofry could you test it again with the nightly?

if this issue is related with #6127 then it should be fixed by PR #6366

**Comment by orbea** [comment]
Given the lack of activity, that this is probably a duplicate of issue https://github.com/libretro/RetroArch/issues/6127 and was likely fixed in PR https://github.com/libretro/RetroArch/pull/6366 I am going to close this issue. Please let us know if its still a problem!
