### ISSUE TITLE
[1.7.6] (windows) Retroarch crashes when netplay is started

### ISSUE THREAD

**Issue by benjaryu** [libretro/RetroArch#8411]
## Description
The latest build of Retroarch  (3 feb 2019) seem to have a critical issue with netplay.
When netplay started as host or client with a (rom runing), retroarch will shut down. The bug seems to happen no matter the core, the core version or the game. It's present on both the 32bit and 64bit windows version. The bug is not present in 1.7.5 and below.

### Expected behavior
In 1.7.5 and below when "Start Netplay as a host" is activated retroarch should remain open and the lobby should properly appear on http://lobby.libretro.com/

### Actual behavior
Retroarch will shut down, and no lobby will be created.

### Steps to reproduce the bug
1. Fresh install of retroarch 1.7.6 on windows
2. Download a core (ie Snes9x 1.59.2 8652f54)
3. Add a file 
4. Run the file
5. Press F1 to open the main menu
6. Go to netplay and "Start Netplay Host"
7. Retroarch 1.7.6 will crash
--

### Bisect Results
The problem is happening in the 1.7.6 release of the 3rd of Feb 2019

### Version/Commit
- RetroArch: [1.7.6/commit: 9750719074]

### Environment information
- OS: Windows 10 Version: 10.0.17134 Build 17134

**Comment by orbea** [comment]
Can you bisect this to see what commit it started in? I can't reproduce this because netplay is broken for me in other ways (Which other people have not been able to reproduce).

**Comment by fr500** [comment]
It's fixed on master.
Fixed it like... 2 hours after 1.7.6 released

**Comment by orbea** [comment]
@benjaryu Can you try a nightly please?

**Comment by Julink13** [comment]
How would I install a nightly version on windows 10?

**Comment by r3pwn** [comment]
I was having the same issue on 1.7.6, fixed it by using the latest nightly...

**Comment by Julink13** [comment]
Using the latest nightly, still getting crashes when starting netplay

**Comment by fr500** [comment]
Start the debug exe, then paste the crash report here.

**Comment by Julink13** [comment]
**This is what I get when  I start netplay, and then load a content (Mario party 6 with Dolphin core)
The launcher works until I load a content, then it crashes and closes.**
[https://pastebin.com/vEMywvi1](url)

**This is what I get when I first load a core, then start netplay and finally load a content (Mario party 6, Dolphin core)
When starting netplay after loading a core I get a black screen but I can still load a content through the top menu, but then when loading the content the launcher just simply crashes like last time.**
[https://pastebin.com/qLUWrAvA](url)

**Comment by fr500** [comment]
our netplay doesn't work with dolphin
so that's a completely different issue

**Comment by JosephSnedeker** [comment]
> I was having the same issue on 1.7.6, fixed it by using the latest nightly...

how do i access the nightlies

**Comment by Julink13** [comment]
> > I was having the same issue on 1.7.6, fixed it by using the latest nightly...
> 
> how do i access the nightlies

Since nobody responded when I asked that question, I will gladly help you. You can use https://stellarupdater.github.io/ , It will help you install nightly versions of RetroArch.

**Comment by Julink13** [comment]
> our netplay doesn't work with dolphin
> so that's a completely different issue

Should I open a new Issue, or is it a definitive issue? just kinda weird having something that crashes your launcher in there.

**Comment by fr500** [comment]
It's not a launcher, it's a complete frontend..

**Comment by LootusMaximus** [comment]
I dont think dolphin netplay is anywhere near possible. N64 and ps1 dont even work right because savestates are too big
