### ISSUE TITLE
iOS 10 & iOS 11 projects missing files

### ISSUE THREAD

**Issue by WeedyWeedSmoker** [libretro/RetroArch#8640]
The "Release" configuration for the iOS 10 and iOS 11 pbxproj (inside the Xcode projects) doesn't include "../../deps/rcheevos/include", which makes them fail at compilation time...

The iOS 10 and iOS 11 static seem to be missing way more files, not only in the "include" section...

**Comment by twinaphex** [comment]
See if this solves the issue -

https://github.com/libretro/RetroArch/commit/c9caa5c39b9e56a50be5291e6d11ccfacb0f5eda

**Comment by WeedyWeedSmoker** [comment]
Thanks @twinaphex  !

You seem to have missed the "RetroArch_iOS10.xcodeproj/project.pbxproj" one, but the iOS 11 one is fixed !

Even after the fix though, all the other projects are missing references to "GCDWebUploader", "GCDWebServer", "WebServer" and many other files that are only referenced in the "RetroArch_iOS11.xcodeproj/project.pbxproj"

Affected projects are (even after the rcheevos fix in "RetroArch_iOS10.xcodeproj/project.pbxproj" that you missed) :
RetroArch_iOS9.xcodeproj
RetroArch_iOS10_static.xcodeproj
RetroArch_iOS10.xcodeproj
RetroArch_iOS11_static.xcodeproj

**Comment by twinaphex** [comment]
OK, is this resolved now @WeedyWeedSmoker ?

**Comment by WeedyWeedSmoker** [comment]
@twinaphex Not yet :

**RetroArch_iOS11_static.xcodeproj** & **RetroArch_iOS10_static.xcodeproj** : First error is
/RetroArch/ui/drivers/cocoa/cocoa_common.m:31:9: 'GCDWebUploader.h' file not found

but after including the required WebServer whole folder, compilation still fails with error:

```
ld: library not found for -lretro_ios
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**RetroArch_iOS10.xcodeproj** : First error is the same, but after including WebServer folder, the error log is:

```
ld: warning: -no_pie ignored for arm64
Undefined symbols for architecture arm64:
  "_CFNetServiceGetTargetHost", referenced from:
      -[GCDWebServer(Extensions) bonjourServerURL] in GCDWebServer.o
  "_CFNetServiceUnscheduleFromRunLoop", referenced from:
      -[GCDWebServer _stop] in GCDWebServer.o
  "_CFNetServiceCancel", referenced from:
      -[GCDWebServer _stop] in GCDWebServer.o
  "_kCFStreamErrorDomainNetServices", referenced from:
      __NetServiceResolveCallBack in GCDWebServer.o
  "_CFNetServiceResolveWithTimeout", referenced from:
      __NetServiceRegisterCallBack in GCDWebServer.o
  "_CFNetServiceScheduleWithRunLoop", referenced from:
      -[GCDWebServer _start:] in GCDWebServer.o
  "_kUTTagClassMIMEType", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServerFunctions.o
  "_CFNetServiceCreate", referenced from:
      -[GCDWebServer _start:] in GCDWebServer.o
  "_kUTTagClassFilenameExtension", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServerFunctions.o
  "_CFHTTPMessageCreateResponse", referenced from:
      +[GCDWebServerConnection initialize] in GCDWebServerConnection.o
      -[GCDWebServerConnection _initializeResponseHeadersWithStatusCode:] in GCDWebServerConnection.o
  "_CFHTTPMessageSetHeaderFieldValue", referenced from:
      -[GCDWebServerConnection _initializeResponseHeadersWithStatusCode:] in GCDWebServerConnection.o
      -[GCDWebServerConnection _finishProcessingRequest:] in GCDWebServerConnection.o
      ___51-[GCDWebServerConnection _finishProcessingRequest:]_block_invoke in GCDWebServerConnection.o
  "_CFHTTPMessageIsHeaderComplete", referenced from:
      ___64-[GCDWebServerConnection(Read) readHeaders:withCompletionBlock:]_block_invoke in GCDWebServerConnection.o
  "_UTTypeCopyPreferredTagWithClass", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServerFunctions.o
  "_UTTypeCreatePreferredIdentifierForTag", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServerFunctions.o
  "_CFHTTPMessageAppendBytes", referenced from:
      ___64-[GCDWebServerConnection(Read) readHeaders:withCompletionBlock:]_block_invoke in GCDWebServerConnection.o
  "_CFNetServiceSetClient", referenced from:
      -[GCDWebServer _start:] in GCDWebServer.o
      -[GCDWebServer _stop] in GCDWebServer.o
  "_CFHTTPMessageCopyAllHeaderFields", referenced from:
      ___45-[GCDWebServerConnection _readRequestHeaders]_block_invoke in GCDWebServerConnection.o
  "_CFNetServiceCreateCopy", referenced from:
      -[GCDWebServer _start:] in GCDWebServer.o
  "_CFHTTPMessageCopyRequestURL", referenced from:
      ___45-[GCDWebServerConnection _readRequestHeaders]_block_invoke in GCDWebServerConnection.o
  "_CFNetServiceRegisterWithOptions", referenced from:
      -[GCDWebServer _start:] in GCDWebServer.o
  "_CFNetServiceGetName", referenced from:
      -[GCDWebServer bonjourName] in GCDWebServer.o
  "_CFNetServiceGetType", referenced from:
      -[GCDWebServer bonjourType] in GCDWebServer.o
  "_CFHTTPMessageCopyRequestMethod", referenced from:
      ___45-[GCDWebServerConnection _readRequestHeaders]_block_invoke in GCDWebServerConnection.o
  "_CFHTTPMessageCreateEmpty", referenced from:
      -[GCDWebServerConnection _readRequestHeaders] in GCDWebServerConnection.o
  "_kCFHTTPVersion1_1", referenced from:
      +[GCDWebServerConnection initialize] in GCDWebServerConnection.o
      -[GCDWebServerConnection _initializeResponseHeadersWithStatusCode:] in GCDWebServerConnection.o
  "_CFHTTPMessageCopySerializedMessage", referenced from:
      +[GCDWebServerConnection initialize] in GCDWebServerConnection.o
      -[GCDWebServerConnection(Write) writeHeadersWithCompletionBlock:] in GCDWebServerConnection.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**RetroArch_iOS9.xcodeproj**, **RetroArch_iOS8.xcodeproj** & **RetroArch_iOS6.xcodeproj** First error is the same, but after including WebServer folder, the error log is:

```
Undefined symbols for architecture armv7:
  "_kCFHTTPVersion1_1", referenced from:
      +[GCDWebServerConnection initialize] in GCDWebServerConnection.o
      -[GCDWebServerConnection _initializeResponseHeadersWithStatusCode:] in GCDWebServerConnection.o
  "_CFHTTPMessageAppendBytes", referenced from:
      ___64-[GCDWebServerConnection(Read) readHeaders:withCompletionBlock:]_block_invoke in GCDWebServerConnection.o
  "_CFNetServiceCreateCopy", referenced from:
      -[GCDWebServer _start:] in GCDWebServer.o
  "_CFHTTPMessageCopyAllHeaderFields", referenced from:
      ___45-[GCDWebServerConnection _readRequestHeaders]_block_invoke in GCDWebServerConnection.o
  "_CFHTTPMessageCreateEmpty", referenced from:
      -[GCDWebServerConnection _readRequestHeaders] in GCDWebServerConnection.o
  "_CFHTTPMessageIsHeaderComplete", referenced from:
      ___64-[GCDWebServerConnection(Read) readHeaders:withCompletionBlock:]_block_invoke in GCDWebServerConnection.o
  "_UTTypeCopyPreferredTagWithClass", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServerFunctions.o
  "_CFHTTPMessageSetHeaderFieldValue", referenced from:
      -[GCDWebServerConnection _initializeResponseHeadersWithStatusCode:] in GCDWebServerConnection.o
      -[GCDWebServerConnection _finishProcessingRequest:] in GCDWebServerConnection.o
      ___51-[GCDWebServerConnection _finishProcessingRequest:]_block_invoke in GCDWebServerConnection.o
  "_CFHTTPMessageCreateResponse", referenced from:
      +[GCDWebServerConnection initialize] in GCDWebServerConnection.o
      -[GCDWebServerConnection _initializeResponseHeadersWithStatusCode:] in GCDWebServerConnection.o
  "_CFNetServiceUnscheduleFromRunLoop", referenced from:
      -[GCDWebServer _stop] in GCDWebServer.o
  "_kCFStreamErrorDomainNetServices", referenced from:
      __NetServiceResolveCallBack in GCDWebServer.o
  "_CFNetServiceResolveWithTimeout", referenced from:
      __NetServiceRegisterCallBack in GCDWebServer.o
  "_CFNetServiceGetTargetHost", referenced from:
      -[GCDWebServer(Extensions) bonjourServerURL] in GCDWebServer.o
  "_UTTypeCreatePreferredIdentifierForTag", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServerFunctions.o
  "_kUTTagClassFilenameExtension", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServerFunctions.o
  "_CFNetServiceCreate", referenced from:
      -[GCDWebServer _start:] in GCDWebServer.o
  "_CFNetServiceSetClient", referenced from:
      -[GCDWebServer _start:] in GCDWebServer.o
      -[GCDWebServer _stop] in GCDWebServer.o
  "_CFNetServiceCancel", referenced from:
      -[GCDWebServer _stop] in GCDWebServer.o
  "_kUTTagClassMIMEType", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServerFunctions.o
  "_CFNetServiceScheduleWithRunLoop", referenced from:
      -[GCDWebServer _start:] in GCDWebServer.o
  "_CFNetServiceGetType", referenced from:
      -[GCDWebServer bonjourType] in GCDWebServer.o
  "_CFHTTPMessageCopyRequestMethod", referenced from:
      ___45-[GCDWebServerConnection _readRequestHeaders]_block_invoke in GCDWebServerConnection.o
  "_CFNetServiceGetName", referenced from:
      -[GCDWebServer bonjourName] in GCDWebServer.o
  "_CFNetServiceRegisterWithOptions", referenced from:
      -[GCDWebServer _start:] in GCDWebServer.o
  "_CFHTTPMessageCopyRequestURL", referenced from:
      ___45-[GCDWebServerConnection _readRequestHeaders]_block_invoke in GCDWebServerConnection.o
  "_CFHTTPMessageCopySerializedMessage", referenced from:
      +[GCDWebServerConnection initialize] in GCDWebServerConnection.o
      -[GCDWebServerConnection(Write) writeHeadersWithCompletionBlock:] in GCDWebServerConnection.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by WeedyWeedSmoker** [comment]
This issue is mostly fixed by https://github.com/libretro/RetroArch/pull/8831

NOT fixed yet :
RetroArch_iOS10_static.xcodeproj
RetroArch_iOS11_static.xcodeproj

I may look into it right now but I fail to grasp the concept of statically linking libaries if we make a different version for each iOS version anyway...

**Comment by twinaphex** [comment]
Yes that's normal, the entire point of the statically linked projects is to statically link a libretro core to RetroArch.
