### ISSUE TITLE
RetroArch Web Player fails with "Module.asm._malloc is undefined"

### ISSUE THREAD

**Issue by Dwedit** [libretro/RetroArch#9230]
## Description

When I attempt to use the RetroArch Web Player (https://web.libretro.com/), it fails to start, and I see an error in the developer console:

```
TypeError: Module.asm._malloc is undefined
line 2 > scriptElement:1:278036
    _malloc https://web.libretro.com/ line 2 > scriptElement:1
    callMain https://web.libretro.com/ line 2 > scriptElement:1
    startRetroArch https://web.libretro.com/libretro.js:141
    onclick https://web.libretro.com/:1
```

### Steps to reproduce the bug

1. Go to https://web.libretro.com/ on Mozilla Firefox 68.0.1
2. Select the 2048 core, let it load, click Run
3. Watch the developer console for errors

### Bisect Results

Sorry, I don't know how to bisect this one, as the web player does not have version selection, and I don't have an emscripten toolchain installed.

### Environment information

- OS: Windows 10, 64-bit
- Browser: Mozilla Firefox 68.0.1

**Comment by Dwedit** [comment]
When I Google the exact error message, the only other result is a Github issue tracker entry for Emscripten: https://github.com/emscripten-core/emscripten/issues/6632, which leads to this article: https://emscripten.org/docs/getting_started/FAQ.html#why-do-functions-in-my-c-c-source-code-vanish-when-i-compile-to-javascript-and-or-i-get-no-functions-to-process

**Comment by twinaphex** [comment]
We will need help fixing this.

**Comment by Dwedit** [comment]
It's especially confusing since according to `wasm-objdump`, "2048_libretro.wasm" is indeed exporting a function named `_malloc`.

So far, I can see these files:
`2048_libretro.wasm`
`2048_libretro.asmjs`
`2048_libretro.js`
`libretro.js`
`browserfs.min.js`

When the browser runs the code, it sees the code living in something called 'ScriptElement', but that turns out to actually be `2048_libretro.js`.  When I look there,  I see `_malloc` defined here:
```
var _malloc = Module["_malloc"] = (function() {
    return Module["asm"]["_malloc"].apply(null, arguments)
});
```
I think it is failing on `Module["asm"]["_malloc"]`.

**Comment by twinaphex** [comment]
Hi, @ToadKing is going to be looking into this issue.

**Comment by ToadKing** [comment]
fixes committed, waiting for builds to make sure they work correctly since it involved an emscripten upgrade.

**Comment by Dwedit** [comment]
It looks like the error about _malloc is gone now!

But now I see a new exception:
```
uncaught exception: abort(TypeError: this.ERRNO_CODES is undefined). Build with -s ASSERTIONS=1 for more info. line 2 > scriptElement:1:246611
    callMain https://web.libretro.com/ line 2 > scriptElement:1
    startRetroArch https://web.libretro.com/libretro.js:26
    onclick https://web.libretro.com/:1
```

**Comment by ToadKing** [comment]
Pushed a fix. It's possible it will take a while for builds to complete since we need to rebuild all cores due to an SDK upgrade.

**Comment by RobLoach** [comment]
Confirmed... Could have a look later tonight.

wasm streaming compile failed: LinkError: WebAssembly.instantiate(): Import #4 module="env" function="_gl_glsl_backend" error: global import must be a number or WebAssembly.Global object
libretro.js:36 falling back to ArrayBuffer instantiation
libretro.js:36 failed to asynchronously prepare wasm: LinkError: WebAssembly.instantiate(): Import #4 module="env" function="_gl_glsl_backend" error: global import must be a number or WebAssembly.Global object
libretro.js:35 LinkError: WebAssembly.instantiate(): Import #4 module="env" function="_gl_glsl_backend" error: global import must be a number or WebAssembly.Global object
libretro.js:36 LinkError: WebAssembly.instantiate(): Import #4 module="env" function="_gl_glsl_backend" error: global import must be a number or WebAssembly.Global object
(index):1 Uncaught (in promise) abort({}). Build with -s ASSERTIONS=1 for more info.
Promise.catch (async)
instantiateArrayBuffer @ VM29:1
(anonymous) @ VM29:1
Promise.catch (async)
doNativeWasm @ VM29:1
(anonymous) @ VM29:1
(anonymous) @ VM29:1
p @ jquery-3.1.0.min.js:2
globalEval @ jquery-3.1.0.min.js:2
text script @ jquery-3.1.0.min.js:4
Nb @ jquery-3.1.0.min.js:4
A @ jquery-3.1.0.min.js:4
(anonymous) @ jquery-3.1.0.min.js:4
load (async)
send @ jquery-3.1.0.min.js:4
ajax @ jquery-3.1.0.min.js:4
r.<computed> @ jquery-3.1.0.min.js:4
getScript @ jquery-3.1.0.min.js:4
(anonymous) @ libretro.js:41
j @ jquery-3.1.0.min.js:2
k @ jquery-3.1.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.1.0.min.js:2
i @ jquery-3.1.0.min.js:2
fireWith @ jquery-3.1.0.min.js:2
fire @ jquery-3.1.0.min.js:2
i @ jquery-3.1.0.min.js:2
fireWith @ jquery-3.1.0.min.js:2
ready @ jquery-3.1.0.min.js:2
R @ jquery-3.1.0.min.js:2
VM29:1 Uncaught TypeError: Cannot read property 'apply' of undefined
    at <anonymous>:1:289090
    at func (<anonymous>:1:22834)
    at callRuntimeCallbacks (<anonymous>:1:14808)
    at ensureInitRuntime (<anonymous>:1:15308)
    at Object.callMain (<anonymous>:1:301874)
    at startRetroArch (libretro.js:26)
    at HTMLButtonElement.onclick ((index):81)
(anonymous) @ VM29:1
func @ VM29:1
callRuntimeCallbacks @ VM29:1
ensureInitRuntime @ VM29:1
callMain @ VM29:1
startRetroArch @ libretro.js:26
onclick @ (index):81

**Comment by Dwedit** [comment]
Still seeing the same exception as 15 days ago when I try out 2048 on the web version.

**Comment by twinaphex** [comment]
OK, let me alert @ToadKing to it. Sucks that it's such a nightmare to get this to work again.

**Comment by twinaphex** [comment]
BTW @Dwedit , it might help if you could directly communicate with us on Discord about this issue so we could get you together with @ToadKing in real-time communication, maybe that way we can progress further.

**Comment by zoltanvb** [comment]
This should not be an issue nowadays (at least when the fix for #17245 lands on the server).

**Comment by zoltanvb** [comment]
Web player works again, and this error is long gone. Can be closed probably.
