### ISSUE TITLE
[PC with RetroPie] Spinning fast a trackball/mouse gets stuck the player (or the pointer) in the middle in games like Millipede or Missile Command.

### ISSUE THREAD

**Issue by fastpop72** [libretro/RetroArch#9325]
## Description

Spinning fast a trackball/mouse gets stuck the player (or the pointer) in the middle in games like Millipede or Missile Command.

### Expected behavior

Expect to move from left to right without stucking in the middle.

### Actual behavior

Player or pointer get often stuck in the middle because RA viewport is limited.

Here a sample of Millipede using FBNeo core:

https://youtu.be/hGwcGIXDDqM

Here's a discussion about the issue on FBNeo repo:

https://github.com/libretro/FBNeo/issues/132

### Steps to reproduce the bug

1. Just start Millipede (FBNeo) or Missile Command (mame2015)
2. Enable Mouse in options
3. Use a trackball (or a mouse) and spin (or move) fast in a direction then the opposite direction.

### Version/Commit

- RetroArch: 1.7.6 (RetroPie)

### Environment information

- OS: Debian Buster with RetroPie

**Comment by barbudreadmon** [comment]
I got confirmation from @twinaphex that mouse polling is limited to RA's viewport, that will be a major issue for playing arcade games with trackballs. 
That design choice makes no sense for me, mouse polling should always return the diff, wherever the mouse is.

**Comment by barbudreadmon** [comment]
This issue was fixed on windows (with dinput driver) a few years ago : https://github.com/libretro/RetroArch/commit/5649f084e33651de479278b856cc8739cde35033

Basically this stuff need to be backported to udev driver.

**Comment by Halvhjearne** [comment]
the problem is the cursor is not "locked" to the game/screen and can move outside the game.
while the cursor is "outside" the game, it will not move inside the game.

i have asked in multiple forums about this, but nobody will or has any answer or solution.

**Comment by fastpop72** [comment]
Yes, it happens using RetroArch.

FBNeo & Mame standalones works well instead....

**Comment by yepyepyep4711** [comment]
> This issue was fixed on windows (with dinput driver) a few years ago : [5649f08](https://github.com/libretro/RetroArch/commit/5649f084e33651de479278b856cc8739cde35033)
> 
> Basically this stuff need to be backported to udev driver.
> 
> Edit : actually, it might be that the following commit is responsible for the current behavior : [135b636](https://github.com/libretro/RetroArch/commit/135b636bd42b2ec01cb4cb2dd42f1f7dc4d901c0)

So... what's the status @barbudreadmon ? Fixed? Not fixed? Fixed only for some systems? I'm interested in Linux systems right now.

**Comment by barbudreadmon** [comment]
It seems fixed on my side, someone else can confirm ?

**Comment by fastpop72** [comment]
I tried now with latest retroarch (source) and latest fbneo core (source).

The problem is still there... if you spin fast the player get stuck in the middle.

**Comment by barbudreadmon** [comment]
@fastpop72 are you sure you used latest retroarch ? iirc retropie is building an old version when updating from sources

**Comment by fastpop72** [comment]
@barbudreadmon Effectively the retropie source of RetroArch point to the 1.8.8 version.

I tested now in Windows with the latest 1.9.0 and seems to work well. Maybe the fix has been added recently...

**Comment by yepyepyep4711** [comment]
> @barbudreadmon Effectively the retropie source of RetroArch point to the 1.8.8 version.
> 
> I tested now in Windows with the latest 1.9.0 and seems to work well. Maybe the fix has been added recently...

I'm afraid the problem is OS-specific, so that's no indication. I'm using the batocera distribution, that comes with Retroarch 1.9.0 and the issue is still present, both with spinner and trackball.

**Comment by barbudreadmon** [comment]
> Retroarch 1.9.0

@yepyepyep4711 nightly or stable ? stable is a bit old already

**Comment by yepyepyep4711** [comment]
> > Retroarch 1.9.0
> 
> @yepyepyep4711 nightly or stable ? stable is a bit old already

I'm sorry, I'd like to amend that last edit. I wasn't seeing a difference because you have to save the configuration and restart for it to take effect. So now the spinner *and* the trackball are working with no interruption. That's grand! Thank you very much! The sensitivity seems to be varying, though. Based on the expected behaviour listed [here](http://wiki.arcadecontrols.com/index.php?title=Spinner_Turn_Count), I had to increase the sensitivity twofold for Arkanoid and threefold for Tempest. All using the same hardware. Any idea what could be causing this?

**Comment by barbudreadmon** [comment]
> Any idea what could be causing this?

Not sure, maybe because the trackball code isn't standardized between those 2 drivers.

**Comment by yepyepyep4711** [comment]
In any case, it works. So this can be closed as far as I'm concerned.

**Comment by asfaleia1966** [comment]
Since this thread is still open, I will reply here.  I just moved my Raspberry PI 4b system from a retropie image to Batocera v35.  I am seeing this same behavior. 

Yepyepyep4711 -  I saw your comments about saving the config after your change, but did not follow what change you made. Would you mind posting it here?

Thanks!!!

**Comment by barbudreadmon** [comment]
>I just moved my Raspberry PI 4b system from a retropie image to Batocera v35. I am seeing this same behavior.

What's the retroarch version bundled in batocera ? Sadly those retrogaming distributions have a tendency to bundle retroarch version that are extremely old.
v1.10 is probably the minimal version for this to work properly.

**Comment by asfaleia1966** [comment]
I’m on v1.10.3. I did find a fix that did work, but the author said it would play havoc with light guns. I don’t have them at the moment, so I am using it.  

global.retroarch.video_windowed_fullscreen = "false" placed in Batocera.conf got me to a trackball and two spinners working.

**Comment by yepyepyep4711** [comment]
> Since this thread is still open, I will reply here. I just moved my Raspberry PI 4b system from a retropie image to Batocera v35. I am seeing this same behavior.
> 
> Yepyepyep4711 - I saw your comments about saving the config after your change, but did not follow what change you made. Would you mind posting it here?
> 
> Thanks!!!

I'm doing this from memory, but if it serves me right and I understand my 2021 self correctly then you want to change your retroarch configuration to use udev as input driver :)

**Comment by asfaleia1966** [comment]
Thanks.  My had my system set up for udev.  I tried changing input and controller settings to no effect.



Dave East

________________________________
