### ISSUE TITLE
Manual Scan - Add Arcade dat File Not Work

### ISSUE THREAD

**Issue by ToniBC** [libretro/RetroArch#9894]
Hi, I'm trying to add the .dat so that the manual scan detects the arcade games but retroarch doesn't load the file. This happens in 1.8.2 and Nightly.

When you click on "Arcade Dat File", it lets you search for the file, but none appears even if you have the file "FinalBurn Neo (ClrMame Pro XML, Arcade only) .dat" on the drive. If you deactivate the file filter in the Retroarch file explorer options, the .dat file appears, but when you select it you try to load it as if it were a game instead of adding the data in the manual scan option.

Thank you.

**Comment by i30817** [comment]
Speaking of the manual scan, anyway to scan without having the bios and devices polluting the list? I can scan the games alone, because i put the games on a different dir\* than the bios, but retroarch then freaks out that the games aren't 'complete'.

Ideally for this setup to work, there would be a way to specify two or more 'arcade dirs', one of which is invisible. There was a way to keep the bios separate from the games in upstream mame by using two paths in the mame.ini 'rompath' with a ';' separator, but this doesn't appear to work with RA MAME.



 \*(btw, the manual scanner should have a option to disable recursion imo)

**Comment by i30817** [comment]
I guess the idea is all the stuff in the same dir, but a arcade dat file containing only the 'games' for filtering?

**Comment by ToniBC** [comment]
I think you were confused as a post @i30817 or what you are commenting is not related to the problem I encountered.

The idea of the manual scanning function in arcade games is the possibility to automatically rename arcade games in the playlist.

To do this, there is an option to dig the FBA or MAME data, but they cannot be loaded. The .dat that I have from FBA works perfectly in clrmamepro and other managers, but when selected with the option of manual scan, Retroarch interprets it as if it were trying to load a rom and launches the core compatible with .dat

**Comment by i30817** [comment]
No it's related. The option to use a MAME dat on the manual scanner implies that it can also used as a filter, which means i could filter 'useless' zips (they're useless because i use split sets).

That is, the manual scanner might have opened the opportunity to 'support' split sets of arcade games in retroarch. 'Just' dump everything but chd's in the same dir (i kept bios separate), the find a split dat containing only the main games roms. and filter.

If the manual scan filter function works that way anyway, the MAME core can tolerate the bios split zip being in the same dir as the game but not on the playlist.

**Comment by i30817** [comment]
btw you can use this .xml here to 'validate' a collection but from the name it might be outdated:
https://github.com/libretro/libretro-database/blob/master/metadat/mame/MAME%202016%20XML%20(Arcade%20Only).xml

**Comment by ToniBC** [comment]
The problem is that it does not load any dat or xml file, Retroarch in that option within "Manual Scan" interprets it as if it loaded a rom or it gives error or launches the core Flycast, because if it is a .dat it interprets it as a game from Naoimi.

**Comment by bslenul** [comment]
Seems to be an issue with the File Browser (at least on Windows, haven't tried yet with my Linux VM):

* In `Settings > Directory > File Browser` if I have it set to `<Default>` it will try to load the .dat with Flycast core.
* If I set it to `F:\Roms` and the .dat is somewhere on my F: drive, no problem.
* If I set it to `F:\Roms` but the .dat is on my C: drive for example, it won't work and try to load it with Flycast.

**Comment by ToniBC** [comment]
Ok, the solution works, the reason is weird, but it works, thanks.

Although I will leave the error because it is something that has to be solved, because everyone will have the same error.

**Comment by bslenul** [comment]
Yup that's just a workaround, you should leave it open until it's fixed! ;)

Just tried on my Linux VM, it seems affected too (minus drive letters conflict of course): if File Browser is set to `<Default>`, it will try to load the .dat with a core, if it's set to anything else it works fine.

**Comment by fr500** [comment]
It's an oooooooooooooooooooooooold issue, I've seen it on android too, loading an overlay would result in RA loading it (I figure some core supports CFG extensions)

**Comment by bslenul** [comment]
Yeah I remember having the same kind of issue a while ago with the Disk Append option, where it starts directly the new disc instead of actually appending it. I thought it was fixed since then :p

**Comment by thericeking** [comment]
I am having the exact same issue as OP. Is this something that can be easily fix? I am about to try the temporary solution but seriously, I was looking forward to manual scanning using DATs.

**Comment by thericeking** [comment]
Workaround did not work for me on Windows 10.

**Comment by bslenul** [comment]
For Windows basically you have 2 conditions basically:

* You must have a path set in `Settings > Directory > File Browser`.
* And have your .dat/.xml on the same drive letter as the path you set for File Browser.

So for example if you set path to E:\Roms, your .dat/.xml must be located somewhere on your E: drive.

**Comment by mstrunk2775** [comment]
I'll confirm this worked for me.  After doing the steps below my playlist was created and the names in the playlist were matched from the dat file.  Before doing these steps I was having an issue where the names in the playlist would just come in as the name of the zip files.  But once the names were good thanks to this thread I was able to use the download thumbnails successfully.

- Windows 10 x64
- Latest version of retroArch v1.8.2 installed to D:\RetroArch
- Roms located at D:\Roms\ARCADE
- Roms scanned/fixed with clrmamepro using D:\FinalBurn Neo (ClrMame Pro XML, Arcade only).dat found at https://github.com/libretro/fbneo/tree/master/dats
- Changed `Settings > Directory > File Browser` to D:\Roms

**Playlist created using retroArch manual scan with these settings.**
- Content Directory = D:\Roms\ARCADE
- System Name = FBNeo - Arcade Games
- Custom System Name = #this field left blank#
- Core = Arcade (FinalBurn Neo)
- File Extensions =  #this field left blank#
- Scan Inside Archives = switch to on/yes
- Arcade DAT File = Browsed to D:\FinalBurn Neo (ClrMame Pro XML, Arcade only).dat
- Overwrite Exisiting Playlist = left at off/no

**Comment by fr500** [comment]
@bslenul actually the disk thing isn't fixed either, I just made it so the file browser starts at the last loaded file directory for that one (and subsystem) so it's less apparent

**Comment by bslenul** [comment]
But the bug should still happen if I navigate to another drive (meaning I go through the top level directory) with the Disk Append option, right? Or I misunderstood your message :p Because I can append a disc properly from another drive right now.

**Comment by fr500** [comment]
Hmmm, then it was probably fixed properly

**Comment by jdgleaver** [comment]
Hi all
This should be fixed by PR #9916
Could you please verify (once it has been merged)?

**Comment by bslenul** [comment]
Works like a charm now! 👍

**Comment by jdgleaver** [comment]
Great - thanks for the confirmation!
